//
//
// Tencent is pleased to support the open source community by making tRPC available.
//
// Copyright (C) 2023 THL A29 Limited, a Tencent company.
// All rights reserved.
//
// If you have downloaded a copy of the tRPC source code from Tencent,
// please note that tRPC source code is licensed under the  Apache 2.0 License,
// A copy of the Apache 2.0 License is included in this file.
//
//

// Code generated by MockGen. DO NOT EDIT.
// Source: helloworld.trpc.go

// Package pb is a generated GoMock package.
package pb

import (
	context "context"
	reflect "reflect"

	client "trpc.group/trpc-go/trpc-go/client"
	gomock "github.com/golang/mock/gomock"
)

// MockGreeterService is a mock of GreeterService interface.
type MockGreeterService struct {
	ctrl     *gomock.Controller
	recorder *MockGreeterServiceMockRecorder
}

// MockGreeterServiceMockRecorder is the mock recorder for MockGreeterService.
type MockGreeterServiceMockRecorder struct {
	mock *MockGreeterService
}

// NewMockGreeterService creates a new mock instance.
func NewMockGreeterService(ctrl *gomock.Controller) *MockGreeterService {
	mock := &MockGreeterService{ctrl: ctrl}
	mock.recorder = &MockGreeterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGreeterService) EXPECT() *MockGreeterServiceMockRecorder {
	return m.recorder
}

// Message mocks base method.
func (m *MockGreeterService) Message(ctx context.Context, req *MessageRequest) (*MessageInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Message", ctx, req)
	ret0, _ := ret[0].(*MessageInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Message indicates an expected call of Message.
func (mr *MockGreeterServiceMockRecorder) Message(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Message", reflect.TypeOf((*MockGreeterService)(nil).Message), ctx, req)
}

// SayHello mocks base method.
func (m *MockGreeterService) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SayHello", ctx, req)
	ret0, _ := ret[0].(*HelloReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SayHello indicates an expected call of SayHello.
func (mr *MockGreeterServiceMockRecorder) SayHello(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SayHello", reflect.TypeOf((*MockGreeterService)(nil).SayHello), ctx, req)
}

// UpdateMessage mocks base method.
func (m *MockGreeterService) UpdateMessage(ctx context.Context, req *UpdateMessageRequest) (*MessageInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMessage", ctx, req)
	ret0, _ := ret[0].(*MessageInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMessage indicates an expected call of UpdateMessage.
func (mr *MockGreeterServiceMockRecorder) UpdateMessage(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMessage", reflect.TypeOf((*MockGreeterService)(nil).UpdateMessage), ctx, req)
}

// UpdateMessageV2 mocks base method.
func (m *MockGreeterService) UpdateMessageV2(ctx context.Context, req *UpdateMessageV2Request) (*MessageInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMessageV2", ctx, req)
	ret0, _ := ret[0].(*MessageInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMessageV2 indicates an expected call of UpdateMessageV2.
func (mr *MockGreeterServiceMockRecorder) UpdateMessageV2(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMessageV2", reflect.TypeOf((*MockGreeterService)(nil).UpdateMessageV2), ctx, req)
}

// MockGreeterClientProxy is a mock of GreeterClientProxy interface.
type MockGreeterClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockGreeterClientProxyMockRecorder
}

// MockGreeterClientProxyMockRecorder is the mock recorder for MockGreeterClientProxy.
type MockGreeterClientProxyMockRecorder struct {
	mock *MockGreeterClientProxy
}

// NewMockGreeterClientProxy creates a new mock instance.
func NewMockGreeterClientProxy(ctrl *gomock.Controller) *MockGreeterClientProxy {
	mock := &MockGreeterClientProxy{ctrl: ctrl}
	mock.recorder = &MockGreeterClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGreeterClientProxy) EXPECT() *MockGreeterClientProxyMockRecorder {
	return m.recorder
}

// Message mocks base method.
func (m *MockGreeterClientProxy) Message(ctx context.Context, req *MessageRequest, opts ...client.Option) (*MessageInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Message", varargs...)
	ret0, _ := ret[0].(*MessageInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Message indicates an expected call of Message.
func (mr *MockGreeterClientProxyMockRecorder) Message(ctx, req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Message", reflect.TypeOf((*MockGreeterClientProxy)(nil).Message), varargs...)
}

// SayHello mocks base method.
func (m *MockGreeterClientProxy) SayHello(ctx context.Context, req *HelloRequest, opts ...client.Option) (*HelloReply, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SayHello", varargs...)
	ret0, _ := ret[0].(*HelloReply)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SayHello indicates an expected call of SayHello.
func (mr *MockGreeterClientProxyMockRecorder) SayHello(ctx, req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SayHello", reflect.TypeOf((*MockGreeterClientProxy)(nil).SayHello), varargs...)
}

// UpdateMessage mocks base method.
func (m *MockGreeterClientProxy) UpdateMessage(ctx context.Context, req *UpdateMessageRequest, opts ...client.Option) (*MessageInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateMessage", varargs...)
	ret0, _ := ret[0].(*MessageInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMessage indicates an expected call of UpdateMessage.
func (mr *MockGreeterClientProxyMockRecorder) UpdateMessage(ctx, req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMessage", reflect.TypeOf((*MockGreeterClientProxy)(nil).UpdateMessage), varargs...)
}

// UpdateMessageV2 mocks base method.
func (m *MockGreeterClientProxy) UpdateMessageV2(ctx context.Context, req *UpdateMessageV2Request, opts ...client.Option) (*MessageInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateMessageV2", varargs...)
	ret0, _ := ret[0].(*MessageInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMessageV2 indicates an expected call of UpdateMessageV2.
func (mr *MockGreeterClientProxyMockRecorder) UpdateMessageV2(ctx, req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMessageV2", reflect.TypeOf((*MockGreeterClientProxy)(nil).UpdateMessageV2), varargs...)
}
