//
//
// Tencent is pleased to support the open source community by making tRPC available.
//
// Copyright (C) 2023 THL A29 Limited, a Tencent company.
// All rights reserved.
//
// If you have downloaded a copy of the tRPC source code from Tencent,
// please note that tRPC source code is licensed under the  Apache 2.0 License,
// A copy of the Apache 2.0 License is included in this file.
//
//

// Code generated by MockGen. DO NOT EDIT.
// Source: helloworld.trpc.go

// Package stream is a generated GoMock package.
package stream

import (
	context "context"
	reflect "reflect"

	client "trpc.group/trpc-go/trpc-go/client"
	gomock "github.com/golang/mock/gomock"
)

// MockTestStreamService is a mock of TestStreamService interface.
type MockTestStreamService struct {
	ctrl     *gomock.Controller
	recorder *MockTestStreamServiceMockRecorder
}

// MockTestStreamServiceMockRecorder is the mock recorder for MockTestStreamService.
type MockTestStreamServiceMockRecorder struct {
	mock *MockTestStreamService
}

// NewMockTestStreamService creates a new mock instance.
func NewMockTestStreamService(ctrl *gomock.Controller) *MockTestStreamService {
	mock := &MockTestStreamService{ctrl: ctrl}
	mock.recorder = &MockTestStreamServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestStreamService) EXPECT() *MockTestStreamServiceMockRecorder {
	return m.recorder
}

// BidirectionalStream mocks base method.
func (m *MockTestStreamService) BidirectionalStream(arg0 TestStream_BidirectionalStreamServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BidirectionalStream", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// BidirectionalStream indicates an expected call of BidirectionalStream.
func (mr *MockTestStreamServiceMockRecorder) BidirectionalStream(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BidirectionalStream", reflect.TypeOf((*MockTestStreamService)(nil).BidirectionalStream), arg0)
}

// ClientStream mocks base method.
func (m *MockTestStreamService) ClientStream(arg0 TestStream_ClientStreamServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientStream", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClientStream indicates an expected call of ClientStream.
func (mr *MockTestStreamServiceMockRecorder) ClientStream(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientStream", reflect.TypeOf((*MockTestStreamService)(nil).ClientStream), arg0)
}

// ServerStream mocks base method.
func (m *MockTestStreamService) ServerStream(arg0 *HelloReq, arg1 TestStream_ServerStreamServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServerStream", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ServerStream indicates an expected call of ServerStream.
func (mr *MockTestStreamServiceMockRecorder) ServerStream(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerStream", reflect.TypeOf((*MockTestStreamService)(nil).ServerStream), arg0, arg1)
}

// UnaryCall mocks base method.
func (m *MockTestStreamService) UnaryCall(ctx context.Context, req *HelloReq) (*HelloRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnaryCall", ctx, req)
	ret0, _ := ret[0].(*HelloRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnaryCall indicates an expected call of UnaryCall.
func (mr *MockTestStreamServiceMockRecorder) UnaryCall(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnaryCall", reflect.TypeOf((*MockTestStreamService)(nil).UnaryCall), ctx, req)
}

// MockTestStream_ClientStreamServer is a mock of TestStream_ClientStreamServer interface.
type MockTestStream_ClientStreamServer struct {
	ctrl     *gomock.Controller
	recorder *MockTestStream_ClientStreamServerMockRecorder
}

// MockTestStream_ClientStreamServerMockRecorder is the mock recorder for MockTestStream_ClientStreamServer.
type MockTestStream_ClientStreamServerMockRecorder struct {
	mock *MockTestStream_ClientStreamServer
}

// NewMockTestStream_ClientStreamServer creates a new mock instance.
func NewMockTestStream_ClientStreamServer(ctrl *gomock.Controller) *MockTestStream_ClientStreamServer {
	mock := &MockTestStream_ClientStreamServer{ctrl: ctrl}
	mock.recorder = &MockTestStream_ClientStreamServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestStream_ClientStreamServer) EXPECT() *MockTestStream_ClientStreamServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockTestStream_ClientStreamServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTestStream_ClientStreamServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTestStream_ClientStreamServer)(nil).Context))
}

// Recv mocks base method.
func (m *MockTestStream_ClientStreamServer) Recv() (*HelloReq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*HelloReq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockTestStream_ClientStreamServerMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockTestStream_ClientStreamServer)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockTestStream_ClientStreamServer) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockTestStream_ClientStreamServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockTestStream_ClientStreamServer)(nil).RecvMsg), m)
}

// SendAndClose mocks base method.
func (m *MockTestStream_ClientStreamServer) SendAndClose(arg0 *HelloRsp) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAndClose", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAndClose indicates an expected call of SendAndClose.
func (mr *MockTestStream_ClientStreamServerMockRecorder) SendAndClose(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAndClose", reflect.TypeOf((*MockTestStream_ClientStreamServer)(nil).SendAndClose), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockTestStream_ClientStreamServer) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockTestStream_ClientStreamServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockTestStream_ClientStreamServer)(nil).SendMsg), m)
}

// MockTestStream_ServerStreamServer is a mock of TestStream_ServerStreamServer interface.
type MockTestStream_ServerStreamServer struct {
	ctrl     *gomock.Controller
	recorder *MockTestStream_ServerStreamServerMockRecorder
}

// MockTestStream_ServerStreamServerMockRecorder is the mock recorder for MockTestStream_ServerStreamServer.
type MockTestStream_ServerStreamServerMockRecorder struct {
	mock *MockTestStream_ServerStreamServer
}

// NewMockTestStream_ServerStreamServer creates a new mock instance.
func NewMockTestStream_ServerStreamServer(ctrl *gomock.Controller) *MockTestStream_ServerStreamServer {
	mock := &MockTestStream_ServerStreamServer{ctrl: ctrl}
	mock.recorder = &MockTestStream_ServerStreamServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestStream_ServerStreamServer) EXPECT() *MockTestStream_ServerStreamServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockTestStream_ServerStreamServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTestStream_ServerStreamServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTestStream_ServerStreamServer)(nil).Context))
}

// RecvMsg mocks base method.
func (m_2 *MockTestStream_ServerStreamServer) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockTestStream_ServerStreamServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockTestStream_ServerStreamServer)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockTestStream_ServerStreamServer) Send(arg0 *HelloRsp) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockTestStream_ServerStreamServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTestStream_ServerStreamServer)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockTestStream_ServerStreamServer) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockTestStream_ServerStreamServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockTestStream_ServerStreamServer)(nil).SendMsg), m)
}

// MockTestStream_BidirectionalStreamServer is a mock of TestStream_BidirectionalStreamServer interface.
type MockTestStream_BidirectionalStreamServer struct {
	ctrl     *gomock.Controller
	recorder *MockTestStream_BidirectionalStreamServerMockRecorder
}

// MockTestStream_BidirectionalStreamServerMockRecorder is the mock recorder for MockTestStream_BidirectionalStreamServer.
type MockTestStream_BidirectionalStreamServerMockRecorder struct {
	mock *MockTestStream_BidirectionalStreamServer
}

// NewMockTestStream_BidirectionalStreamServer creates a new mock instance.
func NewMockTestStream_BidirectionalStreamServer(ctrl *gomock.Controller) *MockTestStream_BidirectionalStreamServer {
	mock := &MockTestStream_BidirectionalStreamServer{ctrl: ctrl}
	mock.recorder = &MockTestStream_BidirectionalStreamServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestStream_BidirectionalStreamServer) EXPECT() *MockTestStream_BidirectionalStreamServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockTestStream_BidirectionalStreamServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTestStream_BidirectionalStreamServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTestStream_BidirectionalStreamServer)(nil).Context))
}

// Recv mocks base method.
func (m *MockTestStream_BidirectionalStreamServer) Recv() (*HelloReq, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*HelloReq)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockTestStream_BidirectionalStreamServerMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockTestStream_BidirectionalStreamServer)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockTestStream_BidirectionalStreamServer) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockTestStream_BidirectionalStreamServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockTestStream_BidirectionalStreamServer)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockTestStream_BidirectionalStreamServer) Send(arg0 *HelloRsp) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockTestStream_BidirectionalStreamServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTestStream_BidirectionalStreamServer)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockTestStream_BidirectionalStreamServer) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockTestStream_BidirectionalStreamServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockTestStream_BidirectionalStreamServer)(nil).SendMsg), m)
}

// MockTestStreamClientProxy is a mock of TestStreamClientProxy interface.
type MockTestStreamClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockTestStreamClientProxyMockRecorder
}

// MockTestStreamClientProxyMockRecorder is the mock recorder for MockTestStreamClientProxy.
type MockTestStreamClientProxyMockRecorder struct {
	mock *MockTestStreamClientProxy
}

// NewMockTestStreamClientProxy creates a new mock instance.
func NewMockTestStreamClientProxy(ctrl *gomock.Controller) *MockTestStreamClientProxy {
	mock := &MockTestStreamClientProxy{ctrl: ctrl}
	mock.recorder = &MockTestStreamClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestStreamClientProxy) EXPECT() *MockTestStreamClientProxyMockRecorder {
	return m.recorder
}

// BidirectionalStream mocks base method.
func (m *MockTestStreamClientProxy) BidirectionalStream(ctx context.Context, opts ...client.Option) (TestStream_BidirectionalStreamClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BidirectionalStream", varargs...)
	ret0, _ := ret[0].(TestStream_BidirectionalStreamClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BidirectionalStream indicates an expected call of BidirectionalStream.
func (mr *MockTestStreamClientProxyMockRecorder) BidirectionalStream(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BidirectionalStream", reflect.TypeOf((*MockTestStreamClientProxy)(nil).BidirectionalStream), varargs...)
}

// ClientStream mocks base method.
func (m *MockTestStreamClientProxy) ClientStream(ctx context.Context, opts ...client.Option) (TestStream_ClientStreamClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ClientStream", varargs...)
	ret0, _ := ret[0].(TestStream_ClientStreamClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClientStream indicates an expected call of ClientStream.
func (mr *MockTestStreamClientProxyMockRecorder) ClientStream(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientStream", reflect.TypeOf((*MockTestStreamClientProxy)(nil).ClientStream), varargs...)
}

// ServerStream mocks base method.
func (m *MockTestStreamClientProxy) ServerStream(ctx context.Context, req *HelloReq, opts ...client.Option) (TestStream_ServerStreamClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ServerStream", varargs...)
	ret0, _ := ret[0].(TestStream_ServerStreamClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServerStream indicates an expected call of ServerStream.
func (mr *MockTestStreamClientProxyMockRecorder) ServerStream(ctx, req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerStream", reflect.TypeOf((*MockTestStreamClientProxy)(nil).ServerStream), varargs...)
}

// UnaryCall mocks base method.
func (m *MockTestStreamClientProxy) UnaryCall(ctx context.Context, req *HelloReq, opts ...client.Option) (*HelloRsp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UnaryCall", varargs...)
	ret0, _ := ret[0].(*HelloRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnaryCall indicates an expected call of UnaryCall.
func (mr *MockTestStreamClientProxyMockRecorder) UnaryCall(ctx, req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnaryCall", reflect.TypeOf((*MockTestStreamClientProxy)(nil).UnaryCall), varargs...)
}

// MockTestStream_ClientStreamClient is a mock of TestStream_ClientStreamClient interface.
type MockTestStream_ClientStreamClient struct {
	ctrl     *gomock.Controller
	recorder *MockTestStream_ClientStreamClientMockRecorder
}

// MockTestStream_ClientStreamClientMockRecorder is the mock recorder for MockTestStream_ClientStreamClient.
type MockTestStream_ClientStreamClientMockRecorder struct {
	mock *MockTestStream_ClientStreamClient
}

// NewMockTestStream_ClientStreamClient creates a new mock instance.
func NewMockTestStream_ClientStreamClient(ctrl *gomock.Controller) *MockTestStream_ClientStreamClient {
	mock := &MockTestStream_ClientStreamClient{ctrl: ctrl}
	mock.recorder = &MockTestStream_ClientStreamClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestStream_ClientStreamClient) EXPECT() *MockTestStream_ClientStreamClientMockRecorder {
	return m.recorder
}

// CloseAndRecv mocks base method.
func (m *MockTestStream_ClientStreamClient) CloseAndRecv() (*HelloRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseAndRecv")
	ret0, _ := ret[0].(*HelloRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseAndRecv indicates an expected call of CloseAndRecv.
func (mr *MockTestStream_ClientStreamClientMockRecorder) CloseAndRecv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAndRecv", reflect.TypeOf((*MockTestStream_ClientStreamClient)(nil).CloseAndRecv))
}

// CloseSend mocks base method.
func (m *MockTestStream_ClientStreamClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockTestStream_ClientStreamClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockTestStream_ClientStreamClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockTestStream_ClientStreamClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTestStream_ClientStreamClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTestStream_ClientStreamClient)(nil).Context))
}

// RecvMsg mocks base method.
func (m_2 *MockTestStream_ClientStreamClient) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockTestStream_ClientStreamClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockTestStream_ClientStreamClient)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockTestStream_ClientStreamClient) Send(arg0 *HelloReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockTestStream_ClientStreamClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTestStream_ClientStreamClient)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockTestStream_ClientStreamClient) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockTestStream_ClientStreamClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockTestStream_ClientStreamClient)(nil).SendMsg), m)
}

// MockTestStream_ServerStreamClient is a mock of TestStream_ServerStreamClient interface.
type MockTestStream_ServerStreamClient struct {
	ctrl     *gomock.Controller
	recorder *MockTestStream_ServerStreamClientMockRecorder
}

// MockTestStream_ServerStreamClientMockRecorder is the mock recorder for MockTestStream_ServerStreamClient.
type MockTestStream_ServerStreamClientMockRecorder struct {
	mock *MockTestStream_ServerStreamClient
}

// NewMockTestStream_ServerStreamClient creates a new mock instance.
func NewMockTestStream_ServerStreamClient(ctrl *gomock.Controller) *MockTestStream_ServerStreamClient {
	mock := &MockTestStream_ServerStreamClient{ctrl: ctrl}
	mock.recorder = &MockTestStream_ServerStreamClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestStream_ServerStreamClient) EXPECT() *MockTestStream_ServerStreamClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockTestStream_ServerStreamClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockTestStream_ServerStreamClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockTestStream_ServerStreamClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockTestStream_ServerStreamClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTestStream_ServerStreamClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTestStream_ServerStreamClient)(nil).Context))
}

// Recv mocks base method.
func (m *MockTestStream_ServerStreamClient) Recv() (*HelloRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*HelloRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockTestStream_ServerStreamClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockTestStream_ServerStreamClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockTestStream_ServerStreamClient) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockTestStream_ServerStreamClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockTestStream_ServerStreamClient)(nil).RecvMsg), m)
}

// SendMsg mocks base method.
func (m_2 *MockTestStream_ServerStreamClient) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockTestStream_ServerStreamClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockTestStream_ServerStreamClient)(nil).SendMsg), m)
}

// MockTestStream_BidirectionalStreamClient is a mock of TestStream_BidirectionalStreamClient interface.
type MockTestStream_BidirectionalStreamClient struct {
	ctrl     *gomock.Controller
	recorder *MockTestStream_BidirectionalStreamClientMockRecorder
}

// MockTestStream_BidirectionalStreamClientMockRecorder is the mock recorder for MockTestStream_BidirectionalStreamClient.
type MockTestStream_BidirectionalStreamClientMockRecorder struct {
	mock *MockTestStream_BidirectionalStreamClient
}

// NewMockTestStream_BidirectionalStreamClient creates a new mock instance.
func NewMockTestStream_BidirectionalStreamClient(ctrl *gomock.Controller) *MockTestStream_BidirectionalStreamClient {
	mock := &MockTestStream_BidirectionalStreamClient{ctrl: ctrl}
	mock.recorder = &MockTestStream_BidirectionalStreamClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestStream_BidirectionalStreamClient) EXPECT() *MockTestStream_BidirectionalStreamClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockTestStream_BidirectionalStreamClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockTestStream_BidirectionalStreamClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockTestStream_BidirectionalStreamClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockTestStream_BidirectionalStreamClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTestStream_BidirectionalStreamClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTestStream_BidirectionalStreamClient)(nil).Context))
}

// Recv mocks base method.
func (m *MockTestStream_BidirectionalStreamClient) Recv() (*HelloRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*HelloRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockTestStream_BidirectionalStreamClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockTestStream_BidirectionalStreamClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockTestStream_BidirectionalStreamClient) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockTestStream_BidirectionalStreamClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockTestStream_BidirectionalStreamClient)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockTestStream_BidirectionalStreamClient) Send(arg0 *HelloReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockTestStream_BidirectionalStreamClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTestStream_BidirectionalStreamClient)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockTestStream_BidirectionalStreamClient) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockTestStream_BidirectionalStreamClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockTestStream_BidirectionalStreamClient)(nil).SendMsg), m)
}
