//
//
// Tencent is pleased to support the open source community by making tRPC available.
//
// Copyright (C) 2023 THL A29 Limited, a Tencent company.
// All rights reserved.
//
// If you have downloaded a copy of the tRPC source code from Tencent,
// please note that tRPC source code is licensed under the  Apache 2.0 License,
// A copy of the Apache 2.0 License is included in this file.
//
//

// Code generated by MockGen. DO NOT EDIT.
// Source: helloworld.trpc.go

// Package proto is a generated GoMock package.
package proto

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockRPCZService is a mock of RPCZService interface.
type MockRPCZService struct {
	ctrl     *gomock.Controller
	recorder *MockRPCZServiceMockRecorder
}

// MockRPCZServiceMockRecorder is the mock recorder for MockRPCZService.
type MockRPCZServiceMockRecorder struct {
	mock *MockRPCZService
}

// NewMockRPCZService creates a new mock instance.
func NewMockRPCZService(ctrl *gomock.Controller) *MockRPCZService {
	mock := &MockRPCZService{ctrl: ctrl}
	mock.recorder = &MockRPCZServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPCZService) EXPECT() *MockRPCZServiceMockRecorder {
	return m.recorder
}

// Hello mocks base method.
func (m *MockRPCZService) Hello(ctx context.Context, req *HelloReq) (*HelloRsp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hello", ctx, req)
	ret0, _ := ret[0].(*HelloRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hello indicates an expected call of Hello.
func (mr *MockRPCZServiceMockRecorder) Hello(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hello", reflect.TypeOf((*MockRPCZService)(nil).Hello), ctx, req)
}

// MockRPCZClientProxy is a mock of RPCZClientProxy interface.
type MockRPCZClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockRPCZClientProxyMockRecorder
}

// MockRPCZClientProxyMockRecorder is the mock recorder for MockRPCZClientProxy.
type MockRPCZClientProxyMockRecorder struct {
	mock *MockRPCZClientProxy
}

// NewMockRPCZClientProxy creates a new mock instance.
func NewMockRPCZClientProxy(ctrl *gomock.Controller) *MockRPCZClientProxy {
	mock := &MockRPCZClientProxy{ctrl: ctrl}
	mock.recorder = &MockRPCZClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRPCZClientProxy) EXPECT() *MockRPCZClientProxyMockRecorder {
	return m.recorder
}

// Hello mocks base method.
func (m *MockRPCZClientProxy) Hello(ctx context.Context, req *HelloReq, opts ...client.Option) (*HelloRsp, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Hello", varargs...)
	ret0, _ := ret[0].(*HelloRsp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hello indicates an expected call of Hello.
func (mr *MockRPCZClientProxyMockRecorder) Hello(ctx, req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hello", reflect.TypeOf((*MockRPCZClientProxy)(nil).Hello), varargs...)
}
