//
//
// Tencent is pleased to support the open source community by making tRPC available.
//
// Copyright (C) 2023 THL A29 Limited, a Tencent company.
// All rights reserved.
//
// If you have downloaded a copy of the tRPC source code from Tencent,
// please note that tRPC source code is licensed under the  Apache 2.0 License,
// A copy of the Apache 2.0 License is included in this file.
//
//

// Code generated by MockGen. DO NOT EDIT.
// Source: search.trpc.go

// Package reflection is a generated GoMock package.
package reflection

import (
	context "context"
	reflect "reflect"

	client "trpc.group/trpc-go/trpc-go/client"
	gomock "github.com/golang/mock/gomock"
)

// MockSearchService is a mock of SearchService interface.
type MockSearchService struct {
	ctrl     *gomock.Controller
	recorder *MockSearchServiceMockRecorder
}

// MockSearchServiceMockRecorder is the mock recorder for MockSearchService.
type MockSearchServiceMockRecorder struct {
	mock *MockSearchService
}

// NewMockSearchService creates a new mock instance.
func NewMockSearchService(ctrl *gomock.Controller) *MockSearchService {
	mock := &MockSearchService{ctrl: ctrl}
	mock.recorder = &MockSearchServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchService) EXPECT() *MockSearchServiceMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockSearchService) Search(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, req)
	ret0, _ := ret[0].(*SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearchServiceMockRecorder) Search(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearchService)(nil).Search), ctx, req)
}

// StreamingSearch mocks base method.
func (m *MockSearchService) StreamingSearch(arg0 Search_StreamingSearchServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamingSearch", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamingSearch indicates an expected call of StreamingSearch.
func (mr *MockSearchServiceMockRecorder) StreamingSearch(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamingSearch", reflect.TypeOf((*MockSearchService)(nil).StreamingSearch), arg0)
}

// MockSearch_StreamingSearchServer is a mock of Search_StreamingSearchServer interface.
type MockSearch_StreamingSearchServer struct {
	ctrl     *gomock.Controller
	recorder *MockSearch_StreamingSearchServerMockRecorder
}

// MockSearch_StreamingSearchServerMockRecorder is the mock recorder for MockSearch_StreamingSearchServer.
type MockSearch_StreamingSearchServerMockRecorder struct {
	mock *MockSearch_StreamingSearchServer
}

// NewMockSearch_StreamingSearchServer creates a new mock instance.
func NewMockSearch_StreamingSearchServer(ctrl *gomock.Controller) *MockSearch_StreamingSearchServer {
	mock := &MockSearch_StreamingSearchServer{ctrl: ctrl}
	mock.recorder = &MockSearch_StreamingSearchServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearch_StreamingSearchServer) EXPECT() *MockSearch_StreamingSearchServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockSearch_StreamingSearchServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockSearch_StreamingSearchServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockSearch_StreamingSearchServer)(nil).Context))
}

// Recv mocks base method.
func (m *MockSearch_StreamingSearchServer) Recv() (*SearchRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*SearchRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockSearch_StreamingSearchServerMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockSearch_StreamingSearchServer)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockSearch_StreamingSearchServer) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockSearch_StreamingSearchServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockSearch_StreamingSearchServer)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockSearch_StreamingSearchServer) Send(arg0 *SearchResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockSearch_StreamingSearchServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSearch_StreamingSearchServer)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockSearch_StreamingSearchServer) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockSearch_StreamingSearchServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockSearch_StreamingSearchServer)(nil).SendMsg), m)
}

// MockSearchClientProxy is a mock of SearchClientProxy interface.
type MockSearchClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockSearchClientProxyMockRecorder
}

// MockSearchClientProxyMockRecorder is the mock recorder for MockSearchClientProxy.
type MockSearchClientProxyMockRecorder struct {
	mock *MockSearchClientProxy
}

// NewMockSearchClientProxy creates a new mock instance.
func NewMockSearchClientProxy(ctrl *gomock.Controller) *MockSearchClientProxy {
	mock := &MockSearchClientProxy{ctrl: ctrl}
	mock.recorder = &MockSearchClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchClientProxy) EXPECT() *MockSearchClientProxyMockRecorder {
	return m.recorder
}

// Search mocks base method.
func (m *MockSearchClientProxy) Search(ctx context.Context, req *SearchRequest, opts ...client.Option) (*SearchResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Search", varargs...)
	ret0, _ := ret[0].(*SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockSearchClientProxyMockRecorder) Search(ctx, req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockSearchClientProxy)(nil).Search), varargs...)
}

// StreamingSearch mocks base method.
func (m *MockSearchClientProxy) StreamingSearch(ctx context.Context, opts ...client.Option) (Search_StreamingSearchClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamingSearch", varargs...)
	ret0, _ := ret[0].(Search_StreamingSearchClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamingSearch indicates an expected call of StreamingSearch.
func (mr *MockSearchClientProxyMockRecorder) StreamingSearch(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamingSearch", reflect.TypeOf((*MockSearchClientProxy)(nil).StreamingSearch), varargs...)
}

// MockSearch_StreamingSearchClient is a mock of Search_StreamingSearchClient interface.
type MockSearch_StreamingSearchClient struct {
	ctrl     *gomock.Controller
	recorder *MockSearch_StreamingSearchClientMockRecorder
}

// MockSearch_StreamingSearchClientMockRecorder is the mock recorder for MockSearch_StreamingSearchClient.
type MockSearch_StreamingSearchClientMockRecorder struct {
	mock *MockSearch_StreamingSearchClient
}

// NewMockSearch_StreamingSearchClient creates a new mock instance.
func NewMockSearch_StreamingSearchClient(ctrl *gomock.Controller) *MockSearch_StreamingSearchClient {
	mock := &MockSearch_StreamingSearchClient{ctrl: ctrl}
	mock.recorder = &MockSearch_StreamingSearchClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearch_StreamingSearchClient) EXPECT() *MockSearch_StreamingSearchClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockSearch_StreamingSearchClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockSearch_StreamingSearchClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockSearch_StreamingSearchClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockSearch_StreamingSearchClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockSearch_StreamingSearchClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockSearch_StreamingSearchClient)(nil).Context))
}

// Recv mocks base method.
func (m *MockSearch_StreamingSearchClient) Recv() (*SearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockSearch_StreamingSearchClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockSearch_StreamingSearchClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockSearch_StreamingSearchClient) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockSearch_StreamingSearchClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockSearch_StreamingSearchClient)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockSearch_StreamingSearchClient) Send(arg0 *SearchRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockSearch_StreamingSearchClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockSearch_StreamingSearchClient)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockSearch_StreamingSearchClient) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockSearch_StreamingSearchClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockSearch_StreamingSearchClient)(nil).SendMsg), m)
}
