//
//
// Tencent is pleased to support the open source community by making tRPC available.
//
// Copyright (C) 2023 THL A29 Limited, a Tencent company.
// All rights reserved.
//
// If you have downloaded a copy of the tRPC source code from Tencent,
// please note that tRPC source code is licensed under the  Apache 2.0 License,
// A copy of the Apache 2.0 License is included in this file.
//
//

// Code generated by trpc-go/trpc-go-cmdline v2.6.1. DO NOT EDIT.
// source: search.proto

package reflection

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
	"trpc.group/trpc-go/trpc-go/stream"
)

// START ======================================= Server Service Definition ======================================= START

// SearchService defines service.
type SearchService interface {
	// Search Search is a unary RPC.
	Search(ctx context.Context, req *SearchRequest) (*SearchResponse, error)
	// StreamingSearch StreamingSearch is a streaming RPC.
	StreamingSearch(Search_StreamingSearchServer) error
}

func SearchService_Search_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &SearchRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(SearchService).Search(ctx, reqbody.(*SearchRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

func SearchService_StreamingSearch_Handler(srv interface{}, stream server.Stream) error {
	return srv.(SearchService).StreamingSearch(&searchStreamingSearchServer{stream})
}

type Search_StreamingSearchServer interface {
	Send(*SearchResponse) error
	Recv() (*SearchRequest, error)
	server.Stream
}

type searchStreamingSearchServer struct {
	server.Stream
}

func (x *searchStreamingSearchServer) Send(m *SearchResponse) error {
	return x.Stream.SendMsg(m)
}

func (x *searchStreamingSearchServer) Recv() (*SearchRequest, error) {
	m := new(SearchRequest)
	if err := x.Stream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SearchServer_ServiceDesc descriptor for server.RegisterService.
var SearchServer_ServiceDesc = server.ServiceDesc{
	ServiceName:  "trpc.testdata.reflection.Search",
	HandlerType:  ((*SearchService)(nil)),
	StreamHandle: stream.NewStreamDispatcher(),
	Methods: []server.Method{
		{
			Name: "/trpc.testdata.reflection.Search/Search",
			Func: SearchService_Search_Handler,
		},
	},
	Streams: []server.StreamDesc{
		{
			StreamName:    "/trpc.testdata.reflection.Search/StreamingSearch",
			Handler:       SearchService_StreamingSearch_Handler,
			ServerStreams: true,
		},
	},
}

// RegisterSearchService registers service.
func RegisterSearchService(s server.Service, svr SearchService) {
	if err := s.Register(&SearchServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Search register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedSearch struct{}

// Search Search is a unary RPC.
func (s *UnimplementedSearch) Search(ctx context.Context, req *SearchRequest) (*SearchResponse, error) {
	return nil, errors.New("rpc Search of service Search is not implemented")
}

// StreamingSearch StreamingSearch is a streaming RPC.
func (s *UnimplementedSearch) StreamingSearch(stream Search_StreamingSearchServer) error {
	return errors.New("rpc StreamingSearch of service Search is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// SearchClientProxy defines service client proxy
type SearchClientProxy interface {
	// Search Search is a unary RPC.
	Search(ctx context.Context, req *SearchRequest, opts ...client.Option) (rsp *SearchResponse, err error)
	// StreamingSearch StreamingSearch is a streaming RPC.
	StreamingSearch(ctx context.Context, opts ...client.Option) (Search_StreamingSearchClient, error)
}

type SearchClientProxyImpl struct {
	client       client.Client
	streamClient stream.Client
	opts         []client.Option
}

var NewSearchClientProxy = func(opts ...client.Option) SearchClientProxy {
	return &SearchClientProxyImpl{client: client.DefaultClient, streamClient: stream.DefaultStreamClient, opts: opts}
}

func (c *SearchClientProxyImpl) Search(ctx context.Context, req *SearchRequest, opts ...client.Option) (*SearchResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.testdata.reflection.Search/Search")
	msg.WithCalleeServiceName(SearchServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("testdata")
	msg.WithCalleeServer("reflection")
	msg.WithCalleeService("Search")
	msg.WithCalleeMethod("Search")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SearchResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

func (c *SearchClientProxyImpl) StreamingSearch(ctx context.Context, opts ...client.Option) (Search_StreamingSearchClient, error) {
	ctx, msg := codec.WithCloneMessage(ctx)

	msg.WithClientRPCName("/trpc.testdata.reflection.Search/StreamingSearch")
	msg.WithCalleeServiceName(SearchServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("testdata")
	msg.WithCalleeServer("reflection")
	msg.WithCalleeService("Search")
	msg.WithCalleeMethod("StreamingSearch")
	msg.WithSerializationType(codec.SerializationTypePB)

	clientStreamDesc := &client.ClientStreamDesc{}
	clientStreamDesc.StreamName = "/trpc.testdata.reflection.Search/StreamingSearch"
	clientStreamDesc.ClientStreams = true
	clientStreamDesc.ServerStreams = true

	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)

	stream, err := c.streamClient.NewStream(ctx, clientStreamDesc, "/trpc.testdata.reflection.Search/StreamingSearch", callopts...)
	if err != nil {
		return nil, err
	}
	x := &searchStreamingSearchClient{stream}
	return x, nil
}

type Search_StreamingSearchClient interface {
	Send(*SearchRequest) error
	Recv() (*SearchResponse, error)
	client.ClientStream
}

type searchStreamingSearchClient struct {
	client.ClientStream
}

func (x *searchStreamingSearchClient) Send(m *SearchRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *searchStreamingSearchClient) Recv() (*SearchResponse, error) {
	m := new(SearchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// END ======================================= Client Service Definition ======================================= END
