// Code generated by trpc-go/trpc-go-cmdline v2.9.9. DO NOT EDIT.
// source: player.proto

package proto

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// PlayerService defines service.
type PlayerService interface {
	Update(ctx context.Context, req *UpdateReq) (*UpdateRsp, error)
}

func PlayerService_Update_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &UpdateReq{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(PlayerService).Update(ctx, reqbody.(*UpdateReq))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// PlayerServer_ServiceDesc descriptor for server.RegisterService.
var PlayerServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "keeporder.Player",
	HandlerType: ((*PlayerService)(nil)),
	Methods: []server.Method{
		{
			Name: "/keeporder.Player/Update",
			Func: PlayerService_Update_Handler,
		},
	},
}

// RegisterPlayerService registers service.
func RegisterPlayerService(s server.Service, svr PlayerService) {
	if err := s.Register(&PlayerServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Player register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedPlayer struct{}

func (s *UnimplementedPlayer) Update(ctx context.Context, req *UpdateReq) (*UpdateRsp, error) {
	return nil, errors.New("rpc Update of service Player is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// PlayerClientProxy defines service client proxy
type PlayerClientProxy interface {
	Update(ctx context.Context, req *UpdateReq, opts ...client.Option) (rsp *UpdateRsp, err error)

	KeepOrderUpdate(ctx context.Context, req *UpdateReq, opts ...client.Option) (<-chan *client.RspOrError[UpdateRsp], error)
}

type PlayerClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewPlayerClientProxy = func(opts ...client.Option) PlayerClientProxy {
	return &PlayerClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *PlayerClientProxyImpl) Update(ctx context.Context, req *UpdateReq, opts ...client.Option) (*UpdateRsp, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/keeporder.Player/Update")
	msg.WithCalleeServiceName(PlayerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Player")
	msg.WithCalleeMethod("Update")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &UpdateRsp{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}
func (c *PlayerClientProxyImpl) KeepOrderUpdate(
	ctx context.Context,
	req *UpdateReq,
	opts ...client.Option,
) (<-chan *client.RspOrError[UpdateRsp], error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	// The msg is not deferred put back here, it is put back asynchronously
	// inside the implementation of keeporder client.
	msg.WithClientRPCName("/keeporder.Player/Update")
	msg.WithCalleeServiceName(PlayerServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("")
	msg.WithCalleeServer("")
	msg.WithCalleeService("Player")
	msg.WithCalleeMethod("Update")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	keepOrderClient := client.NewKeepOrderClient[UpdateRsp](c.client)
	return keepOrderClient.KeepOrderInvoke(ctx, req, callopts...)
}

// END ======================================= Client Service Definition ======================================= END
