//
//
// Tencent is pleased to support the open source community by making tRPC available.
//
// Copyright (C) 2023 Tencent.
// All rights reserved.
//
// If you have downloaded a copy of the tRPC source code from Tencent,
// please note that tRPC source code is licensed under the  Apache 2.0 License,
// A copy of the Apache 2.0 License is included in this file.
//
//

// Code generated by trpc-go/trpc-go-cmdline v2.9.9. DO NOT EDIT.
// source: chat.proto

package chat

import (
	"context"
	"errors"
	"fmt"

	_ "trpc.group/trpc-go/trpc-go"
	"trpc.group/trpc-go/trpc-go/client"
	"trpc.group/trpc-go/trpc-go/codec"
	_ "trpc.group/trpc-go/trpc-go/http"
	"trpc.group/trpc-go/trpc-go/server"
)

// START ======================================= Server Service Definition ======================================= START

// ChatService defines service.
type ChatService interface {
	// UnarySayHi UnarySayHi is unary say hi.
	UnarySayHi(ctx context.Context, req *SayHiRequest) (*SayHiResponse, error)
}

func ChatService_UnarySayHi_Handler(svr interface{}, ctx context.Context, f server.FilterFunc) (interface{}, error) {
	req := &SayHiRequest{}
	filters, err := f(req)
	if err != nil {
		return nil, err
	}
	handleFunc := func(ctx context.Context, reqbody interface{}) (interface{}, error) {
		return svr.(ChatService).UnarySayHi(ctx, reqbody.(*SayHiRequest))
	}

	var rsp interface{}
	rsp, err = filters.Filter(ctx, req, handleFunc)
	if err != nil {
		return nil, err
	}
	return rsp, nil
}

// ChatServer_ServiceDesc descriptor for server.RegisterService.
var ChatServer_ServiceDesc = server.ServiceDesc{
	ServiceName: "trpc.examples.chat.Chat",
	HandlerType: ((*ChatService)(nil)),
	Methods: []server.Method{
		{
			Name: "/trpc.examples.chat.Chat/UnarySayHi",
			Func: ChatService_UnarySayHi_Handler,
		},
	},
}

// RegisterChatService registers service.
func RegisterChatService(s server.Service, svr ChatService) {
	if err := s.Register(&ChatServer_ServiceDesc, svr); err != nil {
		panic(fmt.Sprintf("Chat register error:%v", err))
	}
}

// START --------------------------------- Default Unimplemented Server Service --------------------------------- START

type UnimplementedChat struct{}

// UnarySayHi UnarySayHi is unary say hi.
func (s *UnimplementedChat) UnarySayHi(ctx context.Context, req *SayHiRequest) (*SayHiResponse, error) {
	return nil, errors.New("rpc UnarySayHi of service Chat is not implemented")
}

// END --------------------------------- Default Unimplemented Server Service --------------------------------- END

// END ======================================= Server Service Definition ======================================= END

// START ======================================= Client Service Definition ======================================= START

// ChatClientProxy defines service client proxy
type ChatClientProxy interface {
	// UnarySayHi UnarySayHi is unary say hi.
	UnarySayHi(ctx context.Context, req *SayHiRequest, opts ...client.Option) (rsp *SayHiResponse, err error)
}

type ChatClientProxyImpl struct {
	client client.Client
	opts   []client.Option
}

var NewChatClientProxy = func(opts ...client.Option) ChatClientProxy {
	return &ChatClientProxyImpl{client: client.DefaultClient, opts: opts}
}

func (c *ChatClientProxyImpl) UnarySayHi(ctx context.Context, req *SayHiRequest, opts ...client.Option) (*SayHiResponse, error) {
	ctx, msg := codec.WithCloneMessage(ctx)
	defer codec.PutBackMessage(msg)
	msg.WithClientRPCName("/trpc.examples.chat.Chat/UnarySayHi")
	msg.WithCalleeServiceName(ChatServer_ServiceDesc.ServiceName)
	msg.WithCalleeApp("examples")
	msg.WithCalleeServer("chat")
	msg.WithCalleeService("Chat")
	msg.WithCalleeMethod("UnarySayHi")
	msg.WithSerializationType(codec.SerializationTypePB)
	callopts := make([]client.Option, 0, len(c.opts)+len(opts))
	callopts = append(callopts, c.opts...)
	callopts = append(callopts, opts...)
	rsp := &SayHiResponse{}
	if err := c.client.Invoke(ctx, req, rsp, callopts...); err != nil {
		return nil, err
	}
	return rsp, nil
}

// END ======================================= Client Service Definition ======================================= END
