//
//
// Tencent is pleased to support the open source community by making tRPC available.
//
// Copyright (C) 2023 THL A29 Limited, a Tencent company.
// All rights reserved.
//
// If you have downloaded a copy of the tRPC source code from Tencent,
// please note that tRPC source code is licensed under the  Apache 2.0 License,
// A copy of the Apache 2.0 License is included in this file.
//
//

// Code generated by MockGen. DO NOT EDIT.
// Source: echo.trpc.go

// Package echo is a generated GoMock package.
package echo

import (
	context "context"
	reflect "reflect"

	client "trpc.group/trpc-go/trpc-go/client"
	gomock "github.com/golang/mock/gomock"
)

// MockEchoService is a mock of EchoService interface.
type MockEchoService struct {
	ctrl     *gomock.Controller
	recorder *MockEchoServiceMockRecorder
}

// MockEchoServiceMockRecorder is the mock recorder for MockEchoService.
type MockEchoServiceMockRecorder struct {
	mock *MockEchoService
}

// NewMockEchoService creates a new mock instance.
func NewMockEchoService(ctrl *gomock.Controller) *MockEchoService {
	mock := &MockEchoService{ctrl: ctrl}
	mock.recorder = &MockEchoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEchoService) EXPECT() *MockEchoServiceMockRecorder {
	return m.recorder
}

// BidirectionalStreamingEcho mocks base method.
func (m *MockEchoService) BidirectionalStreamingEcho(arg0 Echo_BidirectionalStreamingEchoServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BidirectionalStreamingEcho", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// BidirectionalStreamingEcho indicates an expected call of BidirectionalStreamingEcho.
func (mr *MockEchoServiceMockRecorder) BidirectionalStreamingEcho(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BidirectionalStreamingEcho", reflect.TypeOf((*MockEchoService)(nil).BidirectionalStreamingEcho), arg0)
}

// ClientStreamingEcho mocks base method.
func (m *MockEchoService) ClientStreamingEcho(arg0 Echo_ClientStreamingEchoServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientStreamingEcho", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClientStreamingEcho indicates an expected call of ClientStreamingEcho.
func (mr *MockEchoServiceMockRecorder) ClientStreamingEcho(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientStreamingEcho", reflect.TypeOf((*MockEchoService)(nil).ClientStreamingEcho), arg0)
}

// ServerStreamingEcho mocks base method.
func (m *MockEchoService) ServerStreamingEcho(arg0 *EchoRequest, arg1 Echo_ServerStreamingEchoServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ServerStreamingEcho", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// ServerStreamingEcho indicates an expected call of ServerStreamingEcho.
func (mr *MockEchoServiceMockRecorder) ServerStreamingEcho(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerStreamingEcho", reflect.TypeOf((*MockEchoService)(nil).ServerStreamingEcho), arg0, arg1)
}

// UnaryEcho mocks base method.
func (m *MockEchoService) UnaryEcho(ctx context.Context, req *EchoRequest) (*EchoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnaryEcho", ctx, req)
	ret0, _ := ret[0].(*EchoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnaryEcho indicates an expected call of UnaryEcho.
func (mr *MockEchoServiceMockRecorder) UnaryEcho(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnaryEcho", reflect.TypeOf((*MockEchoService)(nil).UnaryEcho), ctx, req)
}

// MockEcho_ServerStreamingEchoServer is a mock of Echo_ServerStreamingEchoServer interface.
type MockEcho_ServerStreamingEchoServer struct {
	ctrl     *gomock.Controller
	recorder *MockEcho_ServerStreamingEchoServerMockRecorder
}

// MockEcho_ServerStreamingEchoServerMockRecorder is the mock recorder for MockEcho_ServerStreamingEchoServer.
type MockEcho_ServerStreamingEchoServerMockRecorder struct {
	mock *MockEcho_ServerStreamingEchoServer
}

// NewMockEcho_ServerStreamingEchoServer creates a new mock instance.
func NewMockEcho_ServerStreamingEchoServer(ctrl *gomock.Controller) *MockEcho_ServerStreamingEchoServer {
	mock := &MockEcho_ServerStreamingEchoServer{ctrl: ctrl}
	mock.recorder = &MockEcho_ServerStreamingEchoServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEcho_ServerStreamingEchoServer) EXPECT() *MockEcho_ServerStreamingEchoServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockEcho_ServerStreamingEchoServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockEcho_ServerStreamingEchoServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockEcho_ServerStreamingEchoServer)(nil).Context))
}

// RecvMsg mocks base method.
func (m_2 *MockEcho_ServerStreamingEchoServer) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockEcho_ServerStreamingEchoServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockEcho_ServerStreamingEchoServer)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockEcho_ServerStreamingEchoServer) Send(arg0 *EchoResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockEcho_ServerStreamingEchoServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockEcho_ServerStreamingEchoServer)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockEcho_ServerStreamingEchoServer) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockEcho_ServerStreamingEchoServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockEcho_ServerStreamingEchoServer)(nil).SendMsg), m)
}

// MockEcho_ClientStreamingEchoServer is a mock of Echo_ClientStreamingEchoServer interface.
type MockEcho_ClientStreamingEchoServer struct {
	ctrl     *gomock.Controller
	recorder *MockEcho_ClientStreamingEchoServerMockRecorder
}

// MockEcho_ClientStreamingEchoServerMockRecorder is the mock recorder for MockEcho_ClientStreamingEchoServer.
type MockEcho_ClientStreamingEchoServerMockRecorder struct {
	mock *MockEcho_ClientStreamingEchoServer
}

// NewMockEcho_ClientStreamingEchoServer creates a new mock instance.
func NewMockEcho_ClientStreamingEchoServer(ctrl *gomock.Controller) *MockEcho_ClientStreamingEchoServer {
	mock := &MockEcho_ClientStreamingEchoServer{ctrl: ctrl}
	mock.recorder = &MockEcho_ClientStreamingEchoServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEcho_ClientStreamingEchoServer) EXPECT() *MockEcho_ClientStreamingEchoServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockEcho_ClientStreamingEchoServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockEcho_ClientStreamingEchoServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockEcho_ClientStreamingEchoServer)(nil).Context))
}

// Recv mocks base method.
func (m *MockEcho_ClientStreamingEchoServer) Recv() (*EchoRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*EchoRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockEcho_ClientStreamingEchoServerMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockEcho_ClientStreamingEchoServer)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockEcho_ClientStreamingEchoServer) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockEcho_ClientStreamingEchoServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockEcho_ClientStreamingEchoServer)(nil).RecvMsg), m)
}

// SendAndClose mocks base method.
func (m *MockEcho_ClientStreamingEchoServer) SendAndClose(arg0 *EchoResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAndClose", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAndClose indicates an expected call of SendAndClose.
func (mr *MockEcho_ClientStreamingEchoServerMockRecorder) SendAndClose(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAndClose", reflect.TypeOf((*MockEcho_ClientStreamingEchoServer)(nil).SendAndClose), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockEcho_ClientStreamingEchoServer) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockEcho_ClientStreamingEchoServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockEcho_ClientStreamingEchoServer)(nil).SendMsg), m)
}

// MockEcho_BidirectionalStreamingEchoServer is a mock of Echo_BidirectionalStreamingEchoServer interface.
type MockEcho_BidirectionalStreamingEchoServer struct {
	ctrl     *gomock.Controller
	recorder *MockEcho_BidirectionalStreamingEchoServerMockRecorder
}

// MockEcho_BidirectionalStreamingEchoServerMockRecorder is the mock recorder for MockEcho_BidirectionalStreamingEchoServer.
type MockEcho_BidirectionalStreamingEchoServerMockRecorder struct {
	mock *MockEcho_BidirectionalStreamingEchoServer
}

// NewMockEcho_BidirectionalStreamingEchoServer creates a new mock instance.
func NewMockEcho_BidirectionalStreamingEchoServer(ctrl *gomock.Controller) *MockEcho_BidirectionalStreamingEchoServer {
	mock := &MockEcho_BidirectionalStreamingEchoServer{ctrl: ctrl}
	mock.recorder = &MockEcho_BidirectionalStreamingEchoServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEcho_BidirectionalStreamingEchoServer) EXPECT() *MockEcho_BidirectionalStreamingEchoServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockEcho_BidirectionalStreamingEchoServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockEcho_BidirectionalStreamingEchoServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockEcho_BidirectionalStreamingEchoServer)(nil).Context))
}

// Recv mocks base method.
func (m *MockEcho_BidirectionalStreamingEchoServer) Recv() (*EchoRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*EchoRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockEcho_BidirectionalStreamingEchoServerMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockEcho_BidirectionalStreamingEchoServer)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockEcho_BidirectionalStreamingEchoServer) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockEcho_BidirectionalStreamingEchoServerMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockEcho_BidirectionalStreamingEchoServer)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockEcho_BidirectionalStreamingEchoServer) Send(arg0 *EchoResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockEcho_BidirectionalStreamingEchoServerMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockEcho_BidirectionalStreamingEchoServer)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockEcho_BidirectionalStreamingEchoServer) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockEcho_BidirectionalStreamingEchoServerMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockEcho_BidirectionalStreamingEchoServer)(nil).SendMsg), m)
}

// MockEchoClientProxy is a mock of EchoClientProxy interface.
type MockEchoClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockEchoClientProxyMockRecorder
}

// MockEchoClientProxyMockRecorder is the mock recorder for MockEchoClientProxy.
type MockEchoClientProxyMockRecorder struct {
	mock *MockEchoClientProxy
}

// NewMockEchoClientProxy creates a new mock instance.
func NewMockEchoClientProxy(ctrl *gomock.Controller) *MockEchoClientProxy {
	mock := &MockEchoClientProxy{ctrl: ctrl}
	mock.recorder = &MockEchoClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEchoClientProxy) EXPECT() *MockEchoClientProxyMockRecorder {
	return m.recorder
}

// BidirectionalStreamingEcho mocks base method.
func (m *MockEchoClientProxy) BidirectionalStreamingEcho(ctx context.Context, opts ...client.Option) (Echo_BidirectionalStreamingEchoClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "BidirectionalStreamingEcho", varargs...)
	ret0, _ := ret[0].(Echo_BidirectionalStreamingEchoClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BidirectionalStreamingEcho indicates an expected call of BidirectionalStreamingEcho.
func (mr *MockEchoClientProxyMockRecorder) BidirectionalStreamingEcho(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BidirectionalStreamingEcho", reflect.TypeOf((*MockEchoClientProxy)(nil).BidirectionalStreamingEcho), varargs...)
}

// ClientStreamingEcho mocks base method.
func (m *MockEchoClientProxy) ClientStreamingEcho(ctx context.Context, opts ...client.Option) (Echo_ClientStreamingEchoClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ClientStreamingEcho", varargs...)
	ret0, _ := ret[0].(Echo_ClientStreamingEchoClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClientStreamingEcho indicates an expected call of ClientStreamingEcho.
func (mr *MockEchoClientProxyMockRecorder) ClientStreamingEcho(ctx interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientStreamingEcho", reflect.TypeOf((*MockEchoClientProxy)(nil).ClientStreamingEcho), varargs...)
}

// ServerStreamingEcho mocks base method.
func (m *MockEchoClientProxy) ServerStreamingEcho(ctx context.Context, req *EchoRequest, opts ...client.Option) (Echo_ServerStreamingEchoClient, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ServerStreamingEcho", varargs...)
	ret0, _ := ret[0].(Echo_ServerStreamingEchoClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ServerStreamingEcho indicates an expected call of ServerStreamingEcho.
func (mr *MockEchoClientProxyMockRecorder) ServerStreamingEcho(ctx, req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ServerStreamingEcho", reflect.TypeOf((*MockEchoClientProxy)(nil).ServerStreamingEcho), varargs...)
}

// UnaryEcho mocks base method.
func (m *MockEchoClientProxy) UnaryEcho(ctx context.Context, req *EchoRequest, opts ...client.Option) (*EchoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UnaryEcho", varargs...)
	ret0, _ := ret[0].(*EchoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnaryEcho indicates an expected call of UnaryEcho.
func (mr *MockEchoClientProxyMockRecorder) UnaryEcho(ctx, req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnaryEcho", reflect.TypeOf((*MockEchoClientProxy)(nil).UnaryEcho), varargs...)
}

// MockEcho_ServerStreamingEchoClient is a mock of Echo_ServerStreamingEchoClient interface.
type MockEcho_ServerStreamingEchoClient struct {
	ctrl     *gomock.Controller
	recorder *MockEcho_ServerStreamingEchoClientMockRecorder
}

// MockEcho_ServerStreamingEchoClientMockRecorder is the mock recorder for MockEcho_ServerStreamingEchoClient.
type MockEcho_ServerStreamingEchoClientMockRecorder struct {
	mock *MockEcho_ServerStreamingEchoClient
}

// NewMockEcho_ServerStreamingEchoClient creates a new mock instance.
func NewMockEcho_ServerStreamingEchoClient(ctrl *gomock.Controller) *MockEcho_ServerStreamingEchoClient {
	mock := &MockEcho_ServerStreamingEchoClient{ctrl: ctrl}
	mock.recorder = &MockEcho_ServerStreamingEchoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEcho_ServerStreamingEchoClient) EXPECT() *MockEcho_ServerStreamingEchoClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockEcho_ServerStreamingEchoClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockEcho_ServerStreamingEchoClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockEcho_ServerStreamingEchoClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockEcho_ServerStreamingEchoClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockEcho_ServerStreamingEchoClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockEcho_ServerStreamingEchoClient)(nil).Context))
}

// Recv mocks base method.
func (m *MockEcho_ServerStreamingEchoClient) Recv() (*EchoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*EchoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockEcho_ServerStreamingEchoClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockEcho_ServerStreamingEchoClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockEcho_ServerStreamingEchoClient) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockEcho_ServerStreamingEchoClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockEcho_ServerStreamingEchoClient)(nil).RecvMsg), m)
}

// SendMsg mocks base method.
func (m_2 *MockEcho_ServerStreamingEchoClient) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockEcho_ServerStreamingEchoClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockEcho_ServerStreamingEchoClient)(nil).SendMsg), m)
}

// MockEcho_ClientStreamingEchoClient is a mock of Echo_ClientStreamingEchoClient interface.
type MockEcho_ClientStreamingEchoClient struct {
	ctrl     *gomock.Controller
	recorder *MockEcho_ClientStreamingEchoClientMockRecorder
}

// MockEcho_ClientStreamingEchoClientMockRecorder is the mock recorder for MockEcho_ClientStreamingEchoClient.
type MockEcho_ClientStreamingEchoClientMockRecorder struct {
	mock *MockEcho_ClientStreamingEchoClient
}

// NewMockEcho_ClientStreamingEchoClient creates a new mock instance.
func NewMockEcho_ClientStreamingEchoClient(ctrl *gomock.Controller) *MockEcho_ClientStreamingEchoClient {
	mock := &MockEcho_ClientStreamingEchoClient{ctrl: ctrl}
	mock.recorder = &MockEcho_ClientStreamingEchoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEcho_ClientStreamingEchoClient) EXPECT() *MockEcho_ClientStreamingEchoClientMockRecorder {
	return m.recorder
}

// CloseAndRecv mocks base method.
func (m *MockEcho_ClientStreamingEchoClient) CloseAndRecv() (*EchoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseAndRecv")
	ret0, _ := ret[0].(*EchoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseAndRecv indicates an expected call of CloseAndRecv.
func (mr *MockEcho_ClientStreamingEchoClientMockRecorder) CloseAndRecv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAndRecv", reflect.TypeOf((*MockEcho_ClientStreamingEchoClient)(nil).CloseAndRecv))
}

// CloseSend mocks base method.
func (m *MockEcho_ClientStreamingEchoClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockEcho_ClientStreamingEchoClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockEcho_ClientStreamingEchoClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockEcho_ClientStreamingEchoClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockEcho_ClientStreamingEchoClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockEcho_ClientStreamingEchoClient)(nil).Context))
}

// RecvMsg mocks base method.
func (m_2 *MockEcho_ClientStreamingEchoClient) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockEcho_ClientStreamingEchoClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockEcho_ClientStreamingEchoClient)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockEcho_ClientStreamingEchoClient) Send(arg0 *EchoRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockEcho_ClientStreamingEchoClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockEcho_ClientStreamingEchoClient)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockEcho_ClientStreamingEchoClient) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockEcho_ClientStreamingEchoClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockEcho_ClientStreamingEchoClient)(nil).SendMsg), m)
}

// MockEcho_BidirectionalStreamingEchoClient is a mock of Echo_BidirectionalStreamingEchoClient interface.
type MockEcho_BidirectionalStreamingEchoClient struct {
	ctrl     *gomock.Controller
	recorder *MockEcho_BidirectionalStreamingEchoClientMockRecorder
}

// MockEcho_BidirectionalStreamingEchoClientMockRecorder is the mock recorder for MockEcho_BidirectionalStreamingEchoClient.
type MockEcho_BidirectionalStreamingEchoClientMockRecorder struct {
	mock *MockEcho_BidirectionalStreamingEchoClient
}

// NewMockEcho_BidirectionalStreamingEchoClient creates a new mock instance.
func NewMockEcho_BidirectionalStreamingEchoClient(ctrl *gomock.Controller) *MockEcho_BidirectionalStreamingEchoClient {
	mock := &MockEcho_BidirectionalStreamingEchoClient{ctrl: ctrl}
	mock.recorder = &MockEcho_BidirectionalStreamingEchoClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEcho_BidirectionalStreamingEchoClient) EXPECT() *MockEcho_BidirectionalStreamingEchoClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockEcho_BidirectionalStreamingEchoClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockEcho_BidirectionalStreamingEchoClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockEcho_BidirectionalStreamingEchoClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockEcho_BidirectionalStreamingEchoClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockEcho_BidirectionalStreamingEchoClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockEcho_BidirectionalStreamingEchoClient)(nil).Context))
}

// Recv mocks base method.
func (m *MockEcho_BidirectionalStreamingEchoClient) Recv() (*EchoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*EchoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockEcho_BidirectionalStreamingEchoClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockEcho_BidirectionalStreamingEchoClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockEcho_BidirectionalStreamingEchoClient) RecvMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockEcho_BidirectionalStreamingEchoClientMockRecorder) RecvMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockEcho_BidirectionalStreamingEchoClient)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockEcho_BidirectionalStreamingEchoClient) Send(arg0 *EchoRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockEcho_BidirectionalStreamingEchoClientMockRecorder) Send(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockEcho_BidirectionalStreamingEchoClient)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockEcho_BidirectionalStreamingEchoClient) SendMsg(m interface{}) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockEcho_BidirectionalStreamingEchoClientMockRecorder) SendMsg(m interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockEcho_BidirectionalStreamingEchoClient)(nil).SendMsg), m)
}
