//
//
// Tencent is pleased to support the open source community by making tRPC available.
//
// Copyright (C) 2023 THL A29 Limited, a Tencent company.
// All rights reserved.
//
// If you have downloaded a copy of the tRPC source code from Tencent,
// please note that tRPC source code is licensed under the  Apache 2.0 License,
// A copy of the Apache 2.0 License is included in this file.
//
//

// Code generated by MockGen. DO NOT EDIT.
// Source: test.trpc.go
//
// Generated by this command:
//
//	mockgen -destination=test_mock.go -package=protocols --source=test.trpc.go
//

// Package protocols is a generated GoMock package.
package protocols

import (
	context "context"
	reflect "reflect"

	client "trpc.group/trpc-go/trpc-go/client"
	gomock "go.uber.org/mock/gomock"
)

// MockTestTRPCService is a mock of TestTRPCService interface.
type MockTestTRPCService struct {
	ctrl     *gomock.Controller
	recorder *MockTestTRPCServiceMockRecorder
}

// MockTestTRPCServiceMockRecorder is the mock recorder for MockTestTRPCService.
type MockTestTRPCServiceMockRecorder struct {
	mock *MockTestTRPCService
}

// NewMockTestTRPCService creates a new mock instance.
func NewMockTestTRPCService(ctrl *gomock.Controller) *MockTestTRPCService {
	mock := &MockTestTRPCService{ctrl: ctrl}
	mock.recorder = &MockTestTRPCServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestTRPCService) EXPECT() *MockTestTRPCServiceMockRecorder {
	return m.recorder
}

// EmptyCall mocks base method.
func (m *MockTestTRPCService) EmptyCall(ctx context.Context, req *Empty) (*Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EmptyCall", ctx, req)
	ret0, _ := ret[0].(*Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmptyCall indicates an expected call of EmptyCall.
func (mr *MockTestTRPCServiceMockRecorder) EmptyCall(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmptyCall", reflect.TypeOf((*MockTestTRPCService)(nil).EmptyCall), ctx, req)
}

// UnaryCall mocks base method.
func (m *MockTestTRPCService) UnaryCall(ctx context.Context, req *SimpleRequest) (*SimpleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnaryCall", ctx, req)
	ret0, _ := ret[0].(*SimpleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnaryCall indicates an expected call of UnaryCall.
func (mr *MockTestTRPCServiceMockRecorder) UnaryCall(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnaryCall", reflect.TypeOf((*MockTestTRPCService)(nil).UnaryCall), ctx, req)
}

// MockTestStreamingService is a mock of TestStreamingService interface.
type MockTestStreamingService struct {
	ctrl     *gomock.Controller
	recorder *MockTestStreamingServiceMockRecorder
}

// MockTestStreamingServiceMockRecorder is the mock recorder for MockTestStreamingService.
type MockTestStreamingServiceMockRecorder struct {
	mock *MockTestStreamingService
}

// NewMockTestStreamingService creates a new mock instance.
func NewMockTestStreamingService(ctrl *gomock.Controller) *MockTestStreamingService {
	mock := &MockTestStreamingService{ctrl: ctrl}
	mock.recorder = &MockTestStreamingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestStreamingService) EXPECT() *MockTestStreamingServiceMockRecorder {
	return m.recorder
}

// FullDuplexCall mocks base method.
func (m *MockTestStreamingService) FullDuplexCall(arg0 TestStreaming_FullDuplexCallServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FullDuplexCall", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// FullDuplexCall indicates an expected call of FullDuplexCall.
func (mr *MockTestStreamingServiceMockRecorder) FullDuplexCall(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FullDuplexCall", reflect.TypeOf((*MockTestStreamingService)(nil).FullDuplexCall), arg0)
}

// HalfDuplexCall mocks base method.
func (m *MockTestStreamingService) HalfDuplexCall(arg0 TestStreaming_HalfDuplexCallServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HalfDuplexCall", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// HalfDuplexCall indicates an expected call of HalfDuplexCall.
func (mr *MockTestStreamingServiceMockRecorder) HalfDuplexCall(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HalfDuplexCall", reflect.TypeOf((*MockTestStreamingService)(nil).HalfDuplexCall), arg0)
}

// StreamingInputCall mocks base method.
func (m *MockTestStreamingService) StreamingInputCall(arg0 TestStreaming_StreamingInputCallServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamingInputCall", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamingInputCall indicates an expected call of StreamingInputCall.
func (mr *MockTestStreamingServiceMockRecorder) StreamingInputCall(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamingInputCall", reflect.TypeOf((*MockTestStreamingService)(nil).StreamingInputCall), arg0)
}

// StreamingOutputCall mocks base method.
func (m *MockTestStreamingService) StreamingOutputCall(arg0 *StreamingOutputCallRequest, arg1 TestStreaming_StreamingOutputCallServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StreamingOutputCall", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// StreamingOutputCall indicates an expected call of StreamingOutputCall.
func (mr *MockTestStreamingServiceMockRecorder) StreamingOutputCall(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamingOutputCall", reflect.TypeOf((*MockTestStreamingService)(nil).StreamingOutputCall), arg0, arg1)
}

// MockTestStreaming_StreamingOutputCallServer is a mock of TestStreaming_StreamingOutputCallServer interface.
type MockTestStreaming_StreamingOutputCallServer struct {
	ctrl     *gomock.Controller
	recorder *MockTestStreaming_StreamingOutputCallServerMockRecorder
}

// MockTestStreaming_StreamingOutputCallServerMockRecorder is the mock recorder for MockTestStreaming_StreamingOutputCallServer.
type MockTestStreaming_StreamingOutputCallServerMockRecorder struct {
	mock *MockTestStreaming_StreamingOutputCallServer
}

// NewMockTestStreaming_StreamingOutputCallServer creates a new mock instance.
func NewMockTestStreaming_StreamingOutputCallServer(ctrl *gomock.Controller) *MockTestStreaming_StreamingOutputCallServer {
	mock := &MockTestStreaming_StreamingOutputCallServer{ctrl: ctrl}
	mock.recorder = &MockTestStreaming_StreamingOutputCallServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestStreaming_StreamingOutputCallServer) EXPECT() *MockTestStreaming_StreamingOutputCallServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockTestStreaming_StreamingOutputCallServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTestStreaming_StreamingOutputCallServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTestStreaming_StreamingOutputCallServer)(nil).Context))
}

// RecvMsg mocks base method.
func (m_2 *MockTestStreaming_StreamingOutputCallServer) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockTestStreaming_StreamingOutputCallServerMockRecorder) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockTestStreaming_StreamingOutputCallServer)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockTestStreaming_StreamingOutputCallServer) Send(arg0 *StreamingOutputCallResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockTestStreaming_StreamingOutputCallServerMockRecorder) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTestStreaming_StreamingOutputCallServer)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockTestStreaming_StreamingOutputCallServer) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockTestStreaming_StreamingOutputCallServerMockRecorder) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockTestStreaming_StreamingOutputCallServer)(nil).SendMsg), m)
}

// MockTestStreaming_StreamingInputCallServer is a mock of TestStreaming_StreamingInputCallServer interface.
type MockTestStreaming_StreamingInputCallServer struct {
	ctrl     *gomock.Controller
	recorder *MockTestStreaming_StreamingInputCallServerMockRecorder
}

// MockTestStreaming_StreamingInputCallServerMockRecorder is the mock recorder for MockTestStreaming_StreamingInputCallServer.
type MockTestStreaming_StreamingInputCallServerMockRecorder struct {
	mock *MockTestStreaming_StreamingInputCallServer
}

// NewMockTestStreaming_StreamingInputCallServer creates a new mock instance.
func NewMockTestStreaming_StreamingInputCallServer(ctrl *gomock.Controller) *MockTestStreaming_StreamingInputCallServer {
	mock := &MockTestStreaming_StreamingInputCallServer{ctrl: ctrl}
	mock.recorder = &MockTestStreaming_StreamingInputCallServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestStreaming_StreamingInputCallServer) EXPECT() *MockTestStreaming_StreamingInputCallServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockTestStreaming_StreamingInputCallServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTestStreaming_StreamingInputCallServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTestStreaming_StreamingInputCallServer)(nil).Context))
}

// Recv mocks base method.
func (m *MockTestStreaming_StreamingInputCallServer) Recv() (*StreamingInputCallRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*StreamingInputCallRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockTestStreaming_StreamingInputCallServerMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockTestStreaming_StreamingInputCallServer)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockTestStreaming_StreamingInputCallServer) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockTestStreaming_StreamingInputCallServerMockRecorder) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockTestStreaming_StreamingInputCallServer)(nil).RecvMsg), m)
}

// SendAndClose mocks base method.
func (m *MockTestStreaming_StreamingInputCallServer) SendAndClose(arg0 *StreamingInputCallResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAndClose", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAndClose indicates an expected call of SendAndClose.
func (mr *MockTestStreaming_StreamingInputCallServerMockRecorder) SendAndClose(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAndClose", reflect.TypeOf((*MockTestStreaming_StreamingInputCallServer)(nil).SendAndClose), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockTestStreaming_StreamingInputCallServer) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockTestStreaming_StreamingInputCallServerMockRecorder) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockTestStreaming_StreamingInputCallServer)(nil).SendMsg), m)
}

// MockTestStreaming_FullDuplexCallServer is a mock of TestStreaming_FullDuplexCallServer interface.
type MockTestStreaming_FullDuplexCallServer struct {
	ctrl     *gomock.Controller
	recorder *MockTestStreaming_FullDuplexCallServerMockRecorder
}

// MockTestStreaming_FullDuplexCallServerMockRecorder is the mock recorder for MockTestStreaming_FullDuplexCallServer.
type MockTestStreaming_FullDuplexCallServerMockRecorder struct {
	mock *MockTestStreaming_FullDuplexCallServer
}

// NewMockTestStreaming_FullDuplexCallServer creates a new mock instance.
func NewMockTestStreaming_FullDuplexCallServer(ctrl *gomock.Controller) *MockTestStreaming_FullDuplexCallServer {
	mock := &MockTestStreaming_FullDuplexCallServer{ctrl: ctrl}
	mock.recorder = &MockTestStreaming_FullDuplexCallServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestStreaming_FullDuplexCallServer) EXPECT() *MockTestStreaming_FullDuplexCallServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockTestStreaming_FullDuplexCallServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTestStreaming_FullDuplexCallServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTestStreaming_FullDuplexCallServer)(nil).Context))
}

// Recv mocks base method.
func (m *MockTestStreaming_FullDuplexCallServer) Recv() (*StreamingOutputCallRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*StreamingOutputCallRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockTestStreaming_FullDuplexCallServerMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockTestStreaming_FullDuplexCallServer)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockTestStreaming_FullDuplexCallServer) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockTestStreaming_FullDuplexCallServerMockRecorder) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockTestStreaming_FullDuplexCallServer)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockTestStreaming_FullDuplexCallServer) Send(arg0 *StreamingOutputCallResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockTestStreaming_FullDuplexCallServerMockRecorder) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTestStreaming_FullDuplexCallServer)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockTestStreaming_FullDuplexCallServer) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockTestStreaming_FullDuplexCallServerMockRecorder) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockTestStreaming_FullDuplexCallServer)(nil).SendMsg), m)
}

// MockTestStreaming_HalfDuplexCallServer is a mock of TestStreaming_HalfDuplexCallServer interface.
type MockTestStreaming_HalfDuplexCallServer struct {
	ctrl     *gomock.Controller
	recorder *MockTestStreaming_HalfDuplexCallServerMockRecorder
}

// MockTestStreaming_HalfDuplexCallServerMockRecorder is the mock recorder for MockTestStreaming_HalfDuplexCallServer.
type MockTestStreaming_HalfDuplexCallServerMockRecorder struct {
	mock *MockTestStreaming_HalfDuplexCallServer
}

// NewMockTestStreaming_HalfDuplexCallServer creates a new mock instance.
func NewMockTestStreaming_HalfDuplexCallServer(ctrl *gomock.Controller) *MockTestStreaming_HalfDuplexCallServer {
	mock := &MockTestStreaming_HalfDuplexCallServer{ctrl: ctrl}
	mock.recorder = &MockTestStreaming_HalfDuplexCallServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestStreaming_HalfDuplexCallServer) EXPECT() *MockTestStreaming_HalfDuplexCallServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockTestStreaming_HalfDuplexCallServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTestStreaming_HalfDuplexCallServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTestStreaming_HalfDuplexCallServer)(nil).Context))
}

// Recv mocks base method.
func (m *MockTestStreaming_HalfDuplexCallServer) Recv() (*StreamingOutputCallRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*StreamingOutputCallRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockTestStreaming_HalfDuplexCallServerMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockTestStreaming_HalfDuplexCallServer)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockTestStreaming_HalfDuplexCallServer) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockTestStreaming_HalfDuplexCallServerMockRecorder) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockTestStreaming_HalfDuplexCallServer)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockTestStreaming_HalfDuplexCallServer) Send(arg0 *StreamingOutputCallResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockTestStreaming_HalfDuplexCallServerMockRecorder) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTestStreaming_HalfDuplexCallServer)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockTestStreaming_HalfDuplexCallServer) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockTestStreaming_HalfDuplexCallServerMockRecorder) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockTestStreaming_HalfDuplexCallServer)(nil).SendMsg), m)
}

// MockTestHTTPService is a mock of TestHTTPService interface.
type MockTestHTTPService struct {
	ctrl     *gomock.Controller
	recorder *MockTestHTTPServiceMockRecorder
}

// MockTestHTTPServiceMockRecorder is the mock recorder for MockTestHTTPService.
type MockTestHTTPServiceMockRecorder struct {
	mock *MockTestHTTPService
}

// NewMockTestHTTPService creates a new mock instance.
func NewMockTestHTTPService(ctrl *gomock.Controller) *MockTestHTTPService {
	mock := &MockTestHTTPService{ctrl: ctrl}
	mock.recorder = &MockTestHTTPServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestHTTPService) EXPECT() *MockTestHTTPServiceMockRecorder {
	return m.recorder
}

// UnaryCall mocks base method.
func (m *MockTestHTTPService) UnaryCall(ctx context.Context, req *SimpleRequest) (*SimpleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnaryCall", ctx, req)
	ret0, _ := ret[0].(*SimpleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnaryCall indicates an expected call of UnaryCall.
func (mr *MockTestHTTPServiceMockRecorder) UnaryCall(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnaryCall", reflect.TypeOf((*MockTestHTTPService)(nil).UnaryCall), ctx, req)
}

// MockTestRESTfulService is a mock of TestRESTfulService interface.
type MockTestRESTfulService struct {
	ctrl     *gomock.Controller
	recorder *MockTestRESTfulServiceMockRecorder
}

// MockTestRESTfulServiceMockRecorder is the mock recorder for MockTestRESTfulService.
type MockTestRESTfulServiceMockRecorder struct {
	mock *MockTestRESTfulService
}

// NewMockTestRESTfulService creates a new mock instance.
func NewMockTestRESTfulService(ctrl *gomock.Controller) *MockTestRESTfulService {
	mock := &MockTestRESTfulService{ctrl: ctrl}
	mock.recorder = &MockTestRESTfulServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestRESTfulService) EXPECT() *MockTestRESTfulServiceMockRecorder {
	return m.recorder
}

// GetKnowledgeBase mocks base method.
func (m *MockTestRESTfulService) GetKnowledgeBase(ctx context.Context, req *SimpleRequest) (*SimpleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKnowledgeBase", ctx, req)
	ret0, _ := ret[0].(*SimpleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKnowledgeBase indicates an expected call of GetKnowledgeBase.
func (mr *MockTestRESTfulServiceMockRecorder) GetKnowledgeBase(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKnowledgeBase", reflect.TypeOf((*MockTestRESTfulService)(nil).GetKnowledgeBase), ctx, req)
}

// SearchDocument mocks base method.
func (m *MockTestRESTfulService) SearchDocument(ctx context.Context, req *SimpleRequest) (*SimpleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchDocument", ctx, req)
	ret0, _ := ret[0].(*SimpleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchDocument indicates an expected call of SearchDocument.
func (mr *MockTestRESTfulServiceMockRecorder) SearchDocument(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchDocument", reflect.TypeOf((*MockTestRESTfulService)(nil).SearchDocument), ctx, req)
}

// UnaryCall mocks base method.
func (m *MockTestRESTfulService) UnaryCall(ctx context.Context, req *SimpleRequest) (*SimpleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnaryCall", ctx, req)
	ret0, _ := ret[0].(*SimpleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnaryCall indicates an expected call of UnaryCall.
func (mr *MockTestRESTfulServiceMockRecorder) UnaryCall(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnaryCall", reflect.TypeOf((*MockTestRESTfulService)(nil).UnaryCall), ctx, req)
}

// MockTestTRPCClientProxy is a mock of TestTRPCClientProxy interface.
type MockTestTRPCClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockTestTRPCClientProxyMockRecorder
}

// MockTestTRPCClientProxyMockRecorder is the mock recorder for MockTestTRPCClientProxy.
type MockTestTRPCClientProxyMockRecorder struct {
	mock *MockTestTRPCClientProxy
}

// NewMockTestTRPCClientProxy creates a new mock instance.
func NewMockTestTRPCClientProxy(ctrl *gomock.Controller) *MockTestTRPCClientProxy {
	mock := &MockTestTRPCClientProxy{ctrl: ctrl}
	mock.recorder = &MockTestTRPCClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestTRPCClientProxy) EXPECT() *MockTestTRPCClientProxyMockRecorder {
	return m.recorder
}

// EmptyCall mocks base method.
func (m *MockTestTRPCClientProxy) EmptyCall(ctx context.Context, req *Empty, opts ...client.Option) (*Empty, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "EmptyCall", varargs...)
	ret0, _ := ret[0].(*Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EmptyCall indicates an expected call of EmptyCall.
func (mr *MockTestTRPCClientProxyMockRecorder) EmptyCall(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EmptyCall", reflect.TypeOf((*MockTestTRPCClientProxy)(nil).EmptyCall), varargs...)
}

// KeepOrderEmptyCall mocks base method.
func (m *MockTestTRPCClientProxy) KeepOrderEmptyCall(ctx context.Context, req *Empty, opts ...client.Option) (<-chan *client.RspOrError[Empty], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "KeepOrderEmptyCall", varargs...)
	ret0, _ := ret[0].(<-chan *client.RspOrError[Empty])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeepOrderEmptyCall indicates an expected call of KeepOrderEmptyCall.
func (mr *MockTestTRPCClientProxyMockRecorder) KeepOrderEmptyCall(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeepOrderEmptyCall", reflect.TypeOf((*MockTestTRPCClientProxy)(nil).KeepOrderEmptyCall), varargs...)
}

// KeepOrderUnaryCall mocks base method.
func (m *MockTestTRPCClientProxy) KeepOrderUnaryCall(ctx context.Context, req *SimpleRequest, opts ...client.Option) (<-chan *client.RspOrError[SimpleResponse], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "KeepOrderUnaryCall", varargs...)
	ret0, _ := ret[0].(<-chan *client.RspOrError[SimpleResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeepOrderUnaryCall indicates an expected call of KeepOrderUnaryCall.
func (mr *MockTestTRPCClientProxyMockRecorder) KeepOrderUnaryCall(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeepOrderUnaryCall", reflect.TypeOf((*MockTestTRPCClientProxy)(nil).KeepOrderUnaryCall), varargs...)
}

// UnaryCall mocks base method.
func (m *MockTestTRPCClientProxy) UnaryCall(ctx context.Context, req *SimpleRequest, opts ...client.Option) (*SimpleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UnaryCall", varargs...)
	ret0, _ := ret[0].(*SimpleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnaryCall indicates an expected call of UnaryCall.
func (mr *MockTestTRPCClientProxyMockRecorder) UnaryCall(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnaryCall", reflect.TypeOf((*MockTestTRPCClientProxy)(nil).UnaryCall), varargs...)
}

// MockTestStreamingClientProxy is a mock of TestStreamingClientProxy interface.
type MockTestStreamingClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockTestStreamingClientProxyMockRecorder
}

// MockTestStreamingClientProxyMockRecorder is the mock recorder for MockTestStreamingClientProxy.
type MockTestStreamingClientProxyMockRecorder struct {
	mock *MockTestStreamingClientProxy
}

// NewMockTestStreamingClientProxy creates a new mock instance.
func NewMockTestStreamingClientProxy(ctrl *gomock.Controller) *MockTestStreamingClientProxy {
	mock := &MockTestStreamingClientProxy{ctrl: ctrl}
	mock.recorder = &MockTestStreamingClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestStreamingClientProxy) EXPECT() *MockTestStreamingClientProxyMockRecorder {
	return m.recorder
}

// FullDuplexCall mocks base method.
func (m *MockTestStreamingClientProxy) FullDuplexCall(ctx context.Context, opts ...client.Option) (TestStreaming_FullDuplexCallClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FullDuplexCall", varargs...)
	ret0, _ := ret[0].(TestStreaming_FullDuplexCallClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FullDuplexCall indicates an expected call of FullDuplexCall.
func (mr *MockTestStreamingClientProxyMockRecorder) FullDuplexCall(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FullDuplexCall", reflect.TypeOf((*MockTestStreamingClientProxy)(nil).FullDuplexCall), varargs...)
}

// HalfDuplexCall mocks base method.
func (m *MockTestStreamingClientProxy) HalfDuplexCall(ctx context.Context, opts ...client.Option) (TestStreaming_HalfDuplexCallClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "HalfDuplexCall", varargs...)
	ret0, _ := ret[0].(TestStreaming_HalfDuplexCallClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HalfDuplexCall indicates an expected call of HalfDuplexCall.
func (mr *MockTestStreamingClientProxyMockRecorder) HalfDuplexCall(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HalfDuplexCall", reflect.TypeOf((*MockTestStreamingClientProxy)(nil).HalfDuplexCall), varargs...)
}

// StreamingInputCall mocks base method.
func (m *MockTestStreamingClientProxy) StreamingInputCall(ctx context.Context, opts ...client.Option) (TestStreaming_StreamingInputCallClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamingInputCall", varargs...)
	ret0, _ := ret[0].(TestStreaming_StreamingInputCallClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamingInputCall indicates an expected call of StreamingInputCall.
func (mr *MockTestStreamingClientProxyMockRecorder) StreamingInputCall(ctx any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamingInputCall", reflect.TypeOf((*MockTestStreamingClientProxy)(nil).StreamingInputCall), varargs...)
}

// StreamingOutputCall mocks base method.
func (m *MockTestStreamingClientProxy) StreamingOutputCall(ctx context.Context, req *StreamingOutputCallRequest, opts ...client.Option) (TestStreaming_StreamingOutputCallClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamingOutputCall", varargs...)
	ret0, _ := ret[0].(TestStreaming_StreamingOutputCallClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamingOutputCall indicates an expected call of StreamingOutputCall.
func (mr *MockTestStreamingClientProxyMockRecorder) StreamingOutputCall(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamingOutputCall", reflect.TypeOf((*MockTestStreamingClientProxy)(nil).StreamingOutputCall), varargs...)
}

// MockTestStreaming_StreamingOutputCallClient is a mock of TestStreaming_StreamingOutputCallClient interface.
type MockTestStreaming_StreamingOutputCallClient struct {
	ctrl     *gomock.Controller
	recorder *MockTestStreaming_StreamingOutputCallClientMockRecorder
}

// MockTestStreaming_StreamingOutputCallClientMockRecorder is the mock recorder for MockTestStreaming_StreamingOutputCallClient.
type MockTestStreaming_StreamingOutputCallClientMockRecorder struct {
	mock *MockTestStreaming_StreamingOutputCallClient
}

// NewMockTestStreaming_StreamingOutputCallClient creates a new mock instance.
func NewMockTestStreaming_StreamingOutputCallClient(ctrl *gomock.Controller) *MockTestStreaming_StreamingOutputCallClient {
	mock := &MockTestStreaming_StreamingOutputCallClient{ctrl: ctrl}
	mock.recorder = &MockTestStreaming_StreamingOutputCallClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestStreaming_StreamingOutputCallClient) EXPECT() *MockTestStreaming_StreamingOutputCallClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockTestStreaming_StreamingOutputCallClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockTestStreaming_StreamingOutputCallClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockTestStreaming_StreamingOutputCallClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockTestStreaming_StreamingOutputCallClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTestStreaming_StreamingOutputCallClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTestStreaming_StreamingOutputCallClient)(nil).Context))
}

// Recv mocks base method.
func (m *MockTestStreaming_StreamingOutputCallClient) Recv() (*StreamingOutputCallResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*StreamingOutputCallResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockTestStreaming_StreamingOutputCallClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockTestStreaming_StreamingOutputCallClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockTestStreaming_StreamingOutputCallClient) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockTestStreaming_StreamingOutputCallClientMockRecorder) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockTestStreaming_StreamingOutputCallClient)(nil).RecvMsg), m)
}

// SendMsg mocks base method.
func (m_2 *MockTestStreaming_StreamingOutputCallClient) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockTestStreaming_StreamingOutputCallClientMockRecorder) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockTestStreaming_StreamingOutputCallClient)(nil).SendMsg), m)
}

// MockTestStreaming_StreamingInputCallClient is a mock of TestStreaming_StreamingInputCallClient interface.
type MockTestStreaming_StreamingInputCallClient struct {
	ctrl     *gomock.Controller
	recorder *MockTestStreaming_StreamingInputCallClientMockRecorder
}

// MockTestStreaming_StreamingInputCallClientMockRecorder is the mock recorder for MockTestStreaming_StreamingInputCallClient.
type MockTestStreaming_StreamingInputCallClientMockRecorder struct {
	mock *MockTestStreaming_StreamingInputCallClient
}

// NewMockTestStreaming_StreamingInputCallClient creates a new mock instance.
func NewMockTestStreaming_StreamingInputCallClient(ctrl *gomock.Controller) *MockTestStreaming_StreamingInputCallClient {
	mock := &MockTestStreaming_StreamingInputCallClient{ctrl: ctrl}
	mock.recorder = &MockTestStreaming_StreamingInputCallClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestStreaming_StreamingInputCallClient) EXPECT() *MockTestStreaming_StreamingInputCallClientMockRecorder {
	return m.recorder
}

// CloseAndRecv mocks base method.
func (m *MockTestStreaming_StreamingInputCallClient) CloseAndRecv() (*StreamingInputCallResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseAndRecv")
	ret0, _ := ret[0].(*StreamingInputCallResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloseAndRecv indicates an expected call of CloseAndRecv.
func (mr *MockTestStreaming_StreamingInputCallClientMockRecorder) CloseAndRecv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseAndRecv", reflect.TypeOf((*MockTestStreaming_StreamingInputCallClient)(nil).CloseAndRecv))
}

// CloseSend mocks base method.
func (m *MockTestStreaming_StreamingInputCallClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockTestStreaming_StreamingInputCallClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockTestStreaming_StreamingInputCallClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockTestStreaming_StreamingInputCallClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTestStreaming_StreamingInputCallClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTestStreaming_StreamingInputCallClient)(nil).Context))
}

// RecvMsg mocks base method.
func (m_2 *MockTestStreaming_StreamingInputCallClient) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockTestStreaming_StreamingInputCallClientMockRecorder) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockTestStreaming_StreamingInputCallClient)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockTestStreaming_StreamingInputCallClient) Send(arg0 *StreamingInputCallRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockTestStreaming_StreamingInputCallClientMockRecorder) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTestStreaming_StreamingInputCallClient)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockTestStreaming_StreamingInputCallClient) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockTestStreaming_StreamingInputCallClientMockRecorder) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockTestStreaming_StreamingInputCallClient)(nil).SendMsg), m)
}

// MockTestStreaming_FullDuplexCallClient is a mock of TestStreaming_FullDuplexCallClient interface.
type MockTestStreaming_FullDuplexCallClient struct {
	ctrl     *gomock.Controller
	recorder *MockTestStreaming_FullDuplexCallClientMockRecorder
}

// MockTestStreaming_FullDuplexCallClientMockRecorder is the mock recorder for MockTestStreaming_FullDuplexCallClient.
type MockTestStreaming_FullDuplexCallClientMockRecorder struct {
	mock *MockTestStreaming_FullDuplexCallClient
}

// NewMockTestStreaming_FullDuplexCallClient creates a new mock instance.
func NewMockTestStreaming_FullDuplexCallClient(ctrl *gomock.Controller) *MockTestStreaming_FullDuplexCallClient {
	mock := &MockTestStreaming_FullDuplexCallClient{ctrl: ctrl}
	mock.recorder = &MockTestStreaming_FullDuplexCallClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestStreaming_FullDuplexCallClient) EXPECT() *MockTestStreaming_FullDuplexCallClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockTestStreaming_FullDuplexCallClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockTestStreaming_FullDuplexCallClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockTestStreaming_FullDuplexCallClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockTestStreaming_FullDuplexCallClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTestStreaming_FullDuplexCallClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTestStreaming_FullDuplexCallClient)(nil).Context))
}

// Recv mocks base method.
func (m *MockTestStreaming_FullDuplexCallClient) Recv() (*StreamingOutputCallResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*StreamingOutputCallResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockTestStreaming_FullDuplexCallClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockTestStreaming_FullDuplexCallClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockTestStreaming_FullDuplexCallClient) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockTestStreaming_FullDuplexCallClientMockRecorder) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockTestStreaming_FullDuplexCallClient)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockTestStreaming_FullDuplexCallClient) Send(arg0 *StreamingOutputCallRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockTestStreaming_FullDuplexCallClientMockRecorder) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTestStreaming_FullDuplexCallClient)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockTestStreaming_FullDuplexCallClient) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockTestStreaming_FullDuplexCallClientMockRecorder) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockTestStreaming_FullDuplexCallClient)(nil).SendMsg), m)
}

// MockTestStreaming_HalfDuplexCallClient is a mock of TestStreaming_HalfDuplexCallClient interface.
type MockTestStreaming_HalfDuplexCallClient struct {
	ctrl     *gomock.Controller
	recorder *MockTestStreaming_HalfDuplexCallClientMockRecorder
}

// MockTestStreaming_HalfDuplexCallClientMockRecorder is the mock recorder for MockTestStreaming_HalfDuplexCallClient.
type MockTestStreaming_HalfDuplexCallClientMockRecorder struct {
	mock *MockTestStreaming_HalfDuplexCallClient
}

// NewMockTestStreaming_HalfDuplexCallClient creates a new mock instance.
func NewMockTestStreaming_HalfDuplexCallClient(ctrl *gomock.Controller) *MockTestStreaming_HalfDuplexCallClient {
	mock := &MockTestStreaming_HalfDuplexCallClient{ctrl: ctrl}
	mock.recorder = &MockTestStreaming_HalfDuplexCallClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestStreaming_HalfDuplexCallClient) EXPECT() *MockTestStreaming_HalfDuplexCallClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockTestStreaming_HalfDuplexCallClient) CloseSend() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseSend")
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockTestStreaming_HalfDuplexCallClientMockRecorder) CloseSend() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockTestStreaming_HalfDuplexCallClient)(nil).CloseSend))
}

// Context mocks base method.
func (m *MockTestStreaming_HalfDuplexCallClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTestStreaming_HalfDuplexCallClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTestStreaming_HalfDuplexCallClient)(nil).Context))
}

// Recv mocks base method.
func (m *MockTestStreaming_HalfDuplexCallClient) Recv() (*StreamingOutputCallResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Recv")
	ret0, _ := ret[0].(*StreamingOutputCallResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockTestStreaming_HalfDuplexCallClientMockRecorder) Recv() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockTestStreaming_HalfDuplexCallClient)(nil).Recv))
}

// RecvMsg mocks base method.
func (m_2 *MockTestStreaming_HalfDuplexCallClient) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockTestStreaming_HalfDuplexCallClientMockRecorder) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockTestStreaming_HalfDuplexCallClient)(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockTestStreaming_HalfDuplexCallClient) Send(arg0 *StreamingOutputCallRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockTestStreaming_HalfDuplexCallClientMockRecorder) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTestStreaming_HalfDuplexCallClient)(nil).Send), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockTestStreaming_HalfDuplexCallClient) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockTestStreaming_HalfDuplexCallClientMockRecorder) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockTestStreaming_HalfDuplexCallClient)(nil).SendMsg), m)
}

// MockTestHTTPClientProxy is a mock of TestHTTPClientProxy interface.
type MockTestHTTPClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockTestHTTPClientProxyMockRecorder
}

// MockTestHTTPClientProxyMockRecorder is the mock recorder for MockTestHTTPClientProxy.
type MockTestHTTPClientProxyMockRecorder struct {
	mock *MockTestHTTPClientProxy
}

// NewMockTestHTTPClientProxy creates a new mock instance.
func NewMockTestHTTPClientProxy(ctrl *gomock.Controller) *MockTestHTTPClientProxy {
	mock := &MockTestHTTPClientProxy{ctrl: ctrl}
	mock.recorder = &MockTestHTTPClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestHTTPClientProxy) EXPECT() *MockTestHTTPClientProxyMockRecorder {
	return m.recorder
}

// KeepOrderUnaryCall mocks base method.
func (m *MockTestHTTPClientProxy) KeepOrderUnaryCall(ctx context.Context, req *SimpleRequest, opts ...client.Option) (<-chan *client.RspOrError[SimpleResponse], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "KeepOrderUnaryCall", varargs...)
	ret0, _ := ret[0].(<-chan *client.RspOrError[SimpleResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeepOrderUnaryCall indicates an expected call of KeepOrderUnaryCall.
func (mr *MockTestHTTPClientProxyMockRecorder) KeepOrderUnaryCall(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeepOrderUnaryCall", reflect.TypeOf((*MockTestHTTPClientProxy)(nil).KeepOrderUnaryCall), varargs...)
}

// UnaryCall mocks base method.
func (m *MockTestHTTPClientProxy) UnaryCall(ctx context.Context, req *SimpleRequest, opts ...client.Option) (*SimpleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UnaryCall", varargs...)
	ret0, _ := ret[0].(*SimpleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnaryCall indicates an expected call of UnaryCall.
func (mr *MockTestHTTPClientProxyMockRecorder) UnaryCall(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnaryCall", reflect.TypeOf((*MockTestHTTPClientProxy)(nil).UnaryCall), varargs...)
}

// MockTestRESTfulClientProxy is a mock of TestRESTfulClientProxy interface.
type MockTestRESTfulClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockTestRESTfulClientProxyMockRecorder
}

// MockTestRESTfulClientProxyMockRecorder is the mock recorder for MockTestRESTfulClientProxy.
type MockTestRESTfulClientProxyMockRecorder struct {
	mock *MockTestRESTfulClientProxy
}

// NewMockTestRESTfulClientProxy creates a new mock instance.
func NewMockTestRESTfulClientProxy(ctrl *gomock.Controller) *MockTestRESTfulClientProxy {
	mock := &MockTestRESTfulClientProxy{ctrl: ctrl}
	mock.recorder = &MockTestRESTfulClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTestRESTfulClientProxy) EXPECT() *MockTestRESTfulClientProxyMockRecorder {
	return m.recorder
}

// GetKnowledgeBase mocks base method.
func (m *MockTestRESTfulClientProxy) GetKnowledgeBase(ctx context.Context, req *SimpleRequest, opts ...client.Option) (*SimpleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetKnowledgeBase", varargs...)
	ret0, _ := ret[0].(*SimpleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKnowledgeBase indicates an expected call of GetKnowledgeBase.
func (mr *MockTestRESTfulClientProxyMockRecorder) GetKnowledgeBase(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKnowledgeBase", reflect.TypeOf((*MockTestRESTfulClientProxy)(nil).GetKnowledgeBase), varargs...)
}

// KeepOrderGetKnowledgeBase mocks base method.
func (m *MockTestRESTfulClientProxy) KeepOrderGetKnowledgeBase(ctx context.Context, req *SimpleRequest, opts ...client.Option) (<-chan *client.RspOrError[SimpleResponse], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "KeepOrderGetKnowledgeBase", varargs...)
	ret0, _ := ret[0].(<-chan *client.RspOrError[SimpleResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeepOrderGetKnowledgeBase indicates an expected call of KeepOrderGetKnowledgeBase.
func (mr *MockTestRESTfulClientProxyMockRecorder) KeepOrderGetKnowledgeBase(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeepOrderGetKnowledgeBase", reflect.TypeOf((*MockTestRESTfulClientProxy)(nil).KeepOrderGetKnowledgeBase), varargs...)
}

// KeepOrderSearchDocument mocks base method.
func (m *MockTestRESTfulClientProxy) KeepOrderSearchDocument(ctx context.Context, req *SimpleRequest, opts ...client.Option) (<-chan *client.RspOrError[SimpleResponse], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "KeepOrderSearchDocument", varargs...)
	ret0, _ := ret[0].(<-chan *client.RspOrError[SimpleResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeepOrderSearchDocument indicates an expected call of KeepOrderSearchDocument.
func (mr *MockTestRESTfulClientProxyMockRecorder) KeepOrderSearchDocument(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeepOrderSearchDocument", reflect.TypeOf((*MockTestRESTfulClientProxy)(nil).KeepOrderSearchDocument), varargs...)
}

// KeepOrderUnaryCall mocks base method.
func (m *MockTestRESTfulClientProxy) KeepOrderUnaryCall(ctx context.Context, req *SimpleRequest, opts ...client.Option) (<-chan *client.RspOrError[SimpleResponse], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "KeepOrderUnaryCall", varargs...)
	ret0, _ := ret[0].(<-chan *client.RspOrError[SimpleResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeepOrderUnaryCall indicates an expected call of KeepOrderUnaryCall.
func (mr *MockTestRESTfulClientProxyMockRecorder) KeepOrderUnaryCall(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeepOrderUnaryCall", reflect.TypeOf((*MockTestRESTfulClientProxy)(nil).KeepOrderUnaryCall), varargs...)
}

// SearchDocument mocks base method.
func (m *MockTestRESTfulClientProxy) SearchDocument(ctx context.Context, req *SimpleRequest, opts ...client.Option) (*SimpleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SearchDocument", varargs...)
	ret0, _ := ret[0].(*SimpleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchDocument indicates an expected call of SearchDocument.
func (mr *MockTestRESTfulClientProxyMockRecorder) SearchDocument(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchDocument", reflect.TypeOf((*MockTestRESTfulClientProxy)(nil).SearchDocument), varargs...)
}

// UnaryCall mocks base method.
func (m *MockTestRESTfulClientProxy) UnaryCall(ctx context.Context, req *SimpleRequest, opts ...client.Option) (*SimpleResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UnaryCall", varargs...)
	ret0, _ := ret[0].(*SimpleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnaryCall indicates an expected call of UnaryCall.
func (mr *MockTestRESTfulClientProxyMockRecorder) UnaryCall(ctx, req any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnaryCall", reflect.TypeOf((*MockTestRESTfulClientProxy)(nil).UnaryCall), varargs...)
}
