// Code generated by MockGen. DO NOT EDIT.
// Source: echo.trpc.go

// Package echo is a generated GoMock package.
package echo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockEchoService is a mock of EchoService interface.
type MockEchoService struct {
	ctrl     *gomock.Controller
	recorder *MockEchoServiceMockRecorder
}

// MockEchoServiceMockRecorder is the mock recorder for MockEchoService.
type MockEchoServiceMockRecorder struct {
	mock *MockEchoService
}

// NewMockEchoService creates a new mock instance.
func NewMockEchoService(ctrl *gomock.Controller) *MockEchoService {
	mock := &MockEchoService{ctrl: ctrl}
	mock.recorder = &MockEchoServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEchoService) EXPECT() *MockEchoServiceMockRecorder {
	return m.recorder
}

// UnaryEcho mocks base method.
func (m *MockEchoService) UnaryEcho(ctx context.Context, req *EchoRequest) (*EchoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnaryEcho", ctx, req)
	ret0, _ := ret[0].(*EchoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnaryEcho indicates an expected call of UnaryEcho.
func (mr *MockEchoServiceMockRecorder) UnaryEcho(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnaryEcho", reflect.TypeOf((*MockEchoService)(nil).UnaryEcho), ctx, req)
}

// MockEchoClientProxy is a mock of EchoClientProxy interface.
type MockEchoClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockEchoClientProxyMockRecorder
}

// MockEchoClientProxyMockRecorder is the mock recorder for MockEchoClientProxy.
type MockEchoClientProxyMockRecorder struct {
	mock *MockEchoClientProxy
}

// NewMockEchoClientProxy creates a new mock instance.
func NewMockEchoClientProxy(ctrl *gomock.Controller) *MockEchoClientProxy {
	mock := &MockEchoClientProxy{ctrl: ctrl}
	mock.recorder = &MockEchoClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEchoClientProxy) EXPECT() *MockEchoClientProxyMockRecorder {
	return m.recorder
}

// UnaryEcho mocks base method.
func (m *MockEchoClientProxy) UnaryEcho(ctx context.Context, req *EchoRequest, opts ...client.Option) (*EchoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UnaryEcho", varargs...)
	ret0, _ := ret[0].(*EchoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnaryEcho indicates an expected call of UnaryEcho.
func (mr *MockEchoClientProxyMockRecorder) UnaryEcho(ctx, req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnaryEcho", reflect.TypeOf((*MockEchoClientProxy)(nil).UnaryEcho), varargs...)
}
