//
//
// Tencent is pleased to support the open source community by making tRPC available.
//
// Copyright (C) 2023 THL A29 Limited, a Tencent company.
// All rights reserved.
//
// If you have downloaded a copy of the tRPC source code from Tencent,
// please note that tRPC source code is licensed under the  Apache 2.0 License,
// A copy of the Apache 2.0 License is included in this file.
//
//

// Code generated by MockGen. DO NOT EDIT.
// Source: rspobsoleted.trpc.go

// Package proto is a generated GoMock package.
package proto

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	client "trpc.group/trpc-go/trpc-go/client"
)

// MockRspObsoletedExampleService is a mock of RspObsoletedExampleService interface.
type MockRspObsoletedExampleService struct {
	ctrl     *gomock.Controller
	recorder *MockRspObsoletedExampleServiceMockRecorder
}

// MockRspObsoletedExampleServiceMockRecorder is the mock recorder for MockRspObsoletedExampleService.
type MockRspObsoletedExampleServiceMockRecorder struct {
	mock *MockRspObsoletedExampleService
}

// NewMockRspObsoletedExampleService creates a new mock instance.
func NewMockRspObsoletedExampleService(ctrl *gomock.Controller) *MockRspObsoletedExampleService {
	mock := &MockRspObsoletedExampleService{ctrl: ctrl}
	mock.recorder = &MockRspObsoletedExampleServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRspObsoletedExampleService) EXPECT() *MockRspObsoletedExampleServiceMockRecorder {
	return m.recorder
}

// Hello mocks base method.
func (m *MockRspObsoletedExampleService) Hello(ctx context.Context, req *Request) (*Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hello", ctx, req)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hello indicates an expected call of Hello.
func (mr *MockRspObsoletedExampleServiceMockRecorder) Hello(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hello", reflect.TypeOf((*MockRspObsoletedExampleService)(nil).Hello), ctx, req)
}

// MockRspObsoletedExampleClientProxy is a mock of RspObsoletedExampleClientProxy interface.
type MockRspObsoletedExampleClientProxy struct {
	ctrl     *gomock.Controller
	recorder *MockRspObsoletedExampleClientProxyMockRecorder
}

// MockRspObsoletedExampleClientProxyMockRecorder is the mock recorder for MockRspObsoletedExampleClientProxy.
type MockRspObsoletedExampleClientProxyMockRecorder struct {
	mock *MockRspObsoletedExampleClientProxy
}

// NewMockRspObsoletedExampleClientProxy creates a new mock instance.
func NewMockRspObsoletedExampleClientProxy(ctrl *gomock.Controller) *MockRspObsoletedExampleClientProxy {
	mock := &MockRspObsoletedExampleClientProxy{ctrl: ctrl}
	mock.recorder = &MockRspObsoletedExampleClientProxyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRspObsoletedExampleClientProxy) EXPECT() *MockRspObsoletedExampleClientProxyMockRecorder {
	return m.recorder
}

// Hello mocks base method.
func (m *MockRspObsoletedExampleClientProxy) Hello(ctx context.Context, req *Request, opts ...client.Option) (*Response, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Hello", varargs...)
	ret0, _ := ret[0].(*Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hello indicates an expected call of Hello.
func (mr *MockRspObsoletedExampleClientProxyMockRecorder) Hello(ctx, req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hello", reflect.TypeOf((*MockRspObsoletedExampleClientProxy)(nil).Hello), varargs...)
}
