{
 "title": "trpc-robust dashboard",
 "description": "Dashboard for trpc-robust.",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Client: QPS by error code",
   "type": "timeseries",
   "description": "Client QPS by error code.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(Development_trpc_ClientFilter_requests[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "max(Development_trpc_trpc_robust_metrics_cpu_usage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client: P99 and P95",
   "type": "timeseries",
   "description": "P99 and P95 at client side.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(Development_trpc_ClientFilter_time_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(Development_trpc_ClientFilter_time_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Goroutine Schedule Delay in microseconds",
   "type": "timeseries",
   "description": "Average Goroutine Schedule Delay in microseconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "max(Development_trpc_trpc_robust_metrics_avg_request_enqueue_delay_in_microseconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server: Pass/Reject QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(Development_trpc_trpc_robust_metrics_request_pass_count[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(Development_trpc_trpc_robust_metrics_request_rejected_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Priority Threshold",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "avg(Development_trpc_trpc_robust_metrics_max_request_priority_pass_threshold)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}