name: Pull Request Check
on:
  pull_request:
  push:
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: read # Use with `only-new-issues` option.
jobs:
  build:
    name: build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: 1.19
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v -coverprofile=coverage.out ./...
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.out
        flags: unittests
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  golangci:
    name: lint
    runs-on: self-hosted
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest 
          only-new-issues: true
          skip-cache: true # To prevent occasional failure of this action.
  typos:
    name: typos
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: typos 
      uses: crate-ci/typos@master
  go-apidiff:
    if: github.event_name == 'pull_request'
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 
    - uses: actions/setup-go@v4
      with:
        go-version: 1.19
    - uses: joelanford/go-apidiff@main

  # https://github.com/huacnlee/autocorrect-action#enable-reviewdog-for-report
  autocorrect:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@main
    - name: AutoCorrect
      uses: huacnlee/autocorrect-action@main
      # uncomment the following to only check changed file by PR (https://github.com/huacnlee/autocorrect-action#only-check-changed-file-by-pr)
      # with:
      #   args: --lint --no-diff-bg-color $(git diff --diff-filter=AM --name-only ${{ github.event.pull_request.base.sha }}}
    - name: Report ReviewDog
      if: failure()
      uses: huacnlee/autocorrect-action@main
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        reviewdog: true